<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW_ALL</name>
   <tag></tag>
   <elementGuidId>80dc7fb4-1487-4d12-8ad0-fea8c4f851ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-view']/div/div/div/div/div[3]/div[4]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.aa-prrimary.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dcbd5eb-d954-4ff7-ba39-c66b3b379d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/WorkRequest/WorkRequestSapList</value>
      <webElementGuid>fa07a161-0990-4ec1-ac69-bcab1ae06991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aa-prrimary mr-2</value>
      <webElementGuid>84d7ff06-f5f8-452c-89ee-16a89b2d01a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW_ALL</value>
      <webElementGuid>c1ce065c-8533-4fd2-8b26-e7294a05f067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn px-0 py-4&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-md-6 pl-3 mb-3&quot;]/div[@class=&quot;panel h-100 d-flex flex-column px-2 bg-white position-relative&quot;]/div[@class=&quot;d-flex flex-column fixed-panel-no-overflow&quot;]/div[@class=&quot;d-flex justify-content-between align-items-end mt-2 mb-2&quot;]/a[@class=&quot;aa-prrimary mr-2&quot;]</value>
      <webElementGuid>d6477654-deb6-40b1-bdd1-2abfffa401a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div[3]/div[4]/a[2]</value>
      <webElementGuid>6567a574-bf57-419b-8cb1-1cef0e41cc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VIEW_ALL')]</value>
      <webElementGuid>665530ff-5f46-4b2a-9353-3d41b1c52d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH ERP'])[1]/following::a[1]</value>
      <webElementGuid>9e271301-0fb3-40f2-be14-70c280e5240c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[4]/following::a[2]</value>
      <webElementGuid>6eecf126-861f-48b6-9f02-4b3635502d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORK REQUESTS'])[2]/preceding::a[1]</value>
      <webElementGuid>373b75fb-b893-4486-bf47-c7a8d92b1e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Approval'])[1]/preceding::a[1]</value>
      <webElementGuid>9758db95-b1aa-473a-990f-b71104df999a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIEW_ALL']/parent::*</value>
      <webElementGuid>90c66b6b-7f15-4029-b667-754723b38125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/WorkRequest/WorkRequestSapList')])[2]</value>
      <webElementGuid>1a7d6ba8-a332-473d-b56c-4ed538e12a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[2]</value>
      <webElementGuid>68898c5c-778c-4e30-8956-60a5aed13d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/WorkRequest/WorkRequestSapList' and (text() = 'VIEW_ALL' or . = 'VIEW_ALL')]</value>
      <webElementGuid>6fb026d3-c236-46bf-bcc7-7a502431d73b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
