<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT_1_2</name>
   <tag></tag>
   <elementGuidId>7aff5e40-6edf-4228-b72a-257830b59c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nextbtndescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nextbtndescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be68af47-534f-4f19-b5fa-757ecfc67272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28d1e422-9fda-4d7b-8fb9-7253808b52da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next btn btn-primary px-5 font-weight-bold</value>
      <webElementGuid>b053e892-3fef-49ac-95fe-712d11499172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextbtndescription</value>
      <webElementGuid>010f3507-ee24-4241-92b8-5f59ca748b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>83354f81-81d0-4cdd-970a-6644a4cafee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextbtndescription&quot;)</value>
      <webElementGuid>a4de4d15-7617-4406-b1d4-b2b504b73a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nextbtndescription']</value>
      <webElementGuid>a0f05f54-b492-4b75-9f32-34bc62a74e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>e2c6aaf6-fd49-4a3f-b90b-464d1af0d08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK'])[1]/following::button[1]</value>
      <webElementGuid>8531acf9-1e9c-4c12-9d53-b2962fb8ca56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload a photo'])[1]/following::button[2]</value>
      <webElementGuid>b9c47194-09fc-4634-b58a-16c80cb02857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit_Booking'])[1]/preceding::button[1]</value>
      <webElementGuid>637bf8de-acb4-454b-8a7f-b5355b793cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Request'])[1]/preceding::button[2]</value>
      <webElementGuid>50b12db9-f510-4401-bd9d-32304be150d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT']/parent::*</value>
      <webElementGuid>f6f93b29-934c-439c-ab1c-e39563192180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b3dc8d19-4ccb-4b77-a826-57c7700ffec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nextbtndescription' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>f3a117cd-fb2e-464b-b63d-a34136205b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
