<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DRILL DOWN DRILL</name>
   <tag></tag>
   <elementGuidId>e65f72c8-b8d0-4e83-a90e-b7bd5f47e705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline-primary.ml-2.d-flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8acfaa08-6745-4578-ba01-d591d7a3fb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57437a39-b0f3-4826-8501-d268d87c78b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary ml-2 d-flex</value>
      <webElementGuid>744fd561-74d0-42bd-aa27-6aa89fe98f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> DRILL DOWN DRILL</value>
      <webElementGuid>e133e143-4481-4478-9020-1eeb9cf9e57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppContainer1&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;mt-2 px-3&quot;]/div[@class=&quot;border-top border-bottom&quot;]/div[@class=&quot;w-100 py-3&quot;]/div[@class=&quot;flex-column mt-2&quot;]/div[@class=&quot;d-flex align-items-center mt-1&quot;]/button[@class=&quot;btn btn-outline-primary ml-2 d-flex&quot;]</value>
      <webElementGuid>946404cb-09e8-401d-9ca7-03ada3e4b8bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>c7c64d38-ce79-4240-b40c-5a905ec073c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>00c825c0-5249-4848-9244-187cd4bf0142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by description, sort code or plant identifier'])[1]/following::button[1]</value>
      <webElementGuid>45a6e8e1-a15d-4d75-8ff8-4a84367a76b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>d96cbf72-bbb4-42c7-a574-30cd867d06ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' DRILL DOWN DRILL' or . = ' DRILL DOWN DRILL')]</value>
      <webElementGuid>6c1f9df2-bf26-4063-953c-3213389a46da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
