<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EDIT</name>
   <tag></tag>
   <elementGuidId>b6eb09bd-0c3d-4517-a4ad-ec6df365c29e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='editbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>955f0dbb-1598-4413-99ce-43361f051fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editbtn</value>
      <webElementGuid>32a37d25-90dc-4c1c-8bd7-2d0eed5389a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary px-2 font-weight-bold ml-1 btnResize</value>
      <webElementGuid>18aae0ab-8cc1-43b1-b1ce-f38f175b918d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EDIT</value>
      <webElementGuid>e4a2fd7d-3973-4518-a4ba-61887921f0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueApprovalSingleContainer&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 pt-0 px-0 pb-2 d-flex flex-column&quot;]/div[@class=&quot;justify-content-center align-items-center d-none d-sm-block centering py-2&quot;]/button[@id=&quot;editbtn&quot;]</value>
      <webElementGuid>0f293379-5899-4d47-b990-5979f872d92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='editbtn']</value>
      <webElementGuid>ab673642-9b77-4484-b0c9-7f439c9821f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueApprovalSingleContainer']/div/div/div/div/button[3]</value>
      <webElementGuid>5aad89ce-be52-4a4d-b08f-b14f3536b767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REJECT'])[1]/following::button[1]</value>
      <webElementGuid>d54b0ed4-0b98-43f7-88f3-255a5914026b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPROVE'])[1]/following::button[2]</value>
      <webElementGuid>26568228-99c6-49d7-ac4d-eebbaa4c6490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPROVE'])[2]/preceding::button[1]</value>
      <webElementGuid>dbc08f90-3344-4384-bbe3-610ccdfe237d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REJECT'])[2]/preceding::button[2]</value>
      <webElementGuid>8b236860-1929-483b-a890-09d736994d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EDIT']/parent::*</value>
      <webElementGuid>eacdd9d6-04a2-4309-b705-e66d8f73e15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button[3]</value>
      <webElementGuid>e1baf6ba-f75d-42ad-9ac7-47632b25dfff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'editbtn' and (text() = 'EDIT' or . = 'EDIT')]</value>
      <webElementGuid>74fe2d70-aaf9-4228-a4d8-82528379a549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
