<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1f603044-6e33-4daf-839d-0f7ca670714e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='singleApprovalModal']/div/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-header.bg-white.d-flex.py-2.justify-content-between > button.close.aa-primary > img[alt=&quot;Close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b7bddc2-7013-4142-a95a-9c7d303c6c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/close.svg</value>
      <webElementGuid>54bd7c00-6daf-43a4-a083-9321eaf3fda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>bdbf34c3-7679-4743-a149-d766b7cdaa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a185e9b1-190d-4fed-857b-af3ca41686a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>0d1c51f2-eb63-4c72-8e00-83344c7fa876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;singleApprovalModal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content rounded-0&quot;]/div[@class=&quot;modal-header bg-white d-flex py-2 justify-content-between&quot;]/button[@class=&quot;close aa-primary&quot;]/img[1]</value>
      <webElementGuid>55fde5ff-9504-4f28-82c3-cb04e1a6dea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singleApprovalModal']/div/div/div/button/img</value>
      <webElementGuid>7dbbe020-589d-4545-9ebf-f66d5ab8e5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Close'])[2]</value>
      <webElementGuid>cbc8552b-017a-415a-b1ff-8c28889fefa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/button/img</value>
      <webElementGuid>aa3f6c39-7f55-4ca9-8391-12441ad71795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/close.svg' and @alt = 'Close']</value>
      <webElementGuid>b151f8aa-6b40-4484-ad42-8b0d8175eff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
