<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_w-100 form-control round _01bf87</name>
   <tag></tag>
   <elementGuidId>3399c88d-6a11-4e68-af13-03cca79e2135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.w-100.form-control.round.form-control-sm.mb-0.left-modal-text.inpusize.rounded-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ff02be3-bc5f-4a4f-a641-23a6a670a68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1291f7f8-d7ba-43b4-a556-5ee8df88513e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8d10aa5d-da0b-4be0-8167-2711df61cafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 form-control round form-control-sm mb-0 left-modal-text inpusize rounded-0</value>
      <webElementGuid>e8afd32d-aa6c-41a6-96df-8d88734189e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;info&quot;)/div[@class=&quot;overflow-auto form-container px-3&quot;]/div[@class=&quot;row align-items-start py-1 pl-3&quot;]/div[@class=&quot;col-8&quot;]/input[@class=&quot;w-100 form-control round form-control-sm mb-0 left-modal-text inpusize rounded-0&quot;]</value>
      <webElementGuid>402dabcb-1926-441b-a5a8-4e4108fc72a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>78cb8dd4-df8a-44ad-8926-136fab6df7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info']/div/div[6]/div[2]/input</value>
      <webElementGuid>6b1e378d-739f-40a8-b68a-68ce246f692b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>057fef31-be6b-48a5-ab2a-4a009a7e0094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>27d3c10a-10a4-4cd2-bc48-8838e6e084a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
