<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Maintenance request_custom-control-la_316232</name>
   <tag></tag>
   <elementGuidId>57ad5017-8504-45cb-bc0d-36a3c4c1e75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.app.header-fixed.sidebar-fixed.aside-menu-fixed.sidebar-lg-show.brand-minimized.sidebar-minimized.modal-open.pace-done.pace-done:nth-child(2) div.app-body.anglo-scrollbar:nth-child(3) main.main:nth-child(2) div.h-100.position-relative:nth-child(2) div.modal.fade.show:nth-child(3) div.modal-dialog.modal-lg div.modal-content.rounded-0 div.modal-body.p-0 div.h-100 div.card.h-100 div.form-horizontal.mar-top.flex-column.d-flex.h-100.justify-content-start div.card-body.h-100.d-flex.flex-column.pt-0.px-0 div.overflow-auto.anglo-scrollbar div.wiz-list.mt-2 div.d-flex.px-3.col-12.justify-content-center.c-pointer.pt-2.pb-0:nth-child(1) div.w-100.pb-2.border-bottom div:nth-child(4) div.custom-control.custom-checkbox.mb-2 > label.custom-control-label.cursorPointer:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vueAppContainer1']/div[2]/div/div/div/div[2]/div/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>27b7b3ee-8bbe-4e79-8b4f-16a36a6e98d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>followOnWorkRequestID</value>
      <webElementGuid>28193d30-2121-4b60-a313-938a8df2a339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label cursorPointer</value>
      <webElementGuid>32d81129-ae19-4a05-9f62-c7d24a15649b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppContainer1&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;overflow-auto anglo-scrollbar&quot;]/div[@class=&quot;wiz-list mt-2&quot;]/div[@class=&quot;d-flex px-3 col-12 justify-content-center c-pointer pt-2 pb-0&quot;]/div[@class=&quot;w-100  pb-2 border-bottom&quot;]/div[1]/div[@class=&quot;custom-control custom-checkbox mb-2&quot;]/label[@class=&quot;custom-control-label cursorPointer&quot;]</value>
      <webElementGuid>4e9cbc95-1b19-4d99-9b20-18deee1e02e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div/div[2]/div/div/div/div/label</value>
      <webElementGuid>2caaf938-7e85-4ecf-8cdf-9797f36f7a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label</value>
      <webElementGuid>f78be9e4-371a-4599-a2fa-13c719821684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
