<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Centre Plant Code_WorkCenterMain_0c3e15</name>
   <tag></tag>
   <elementGuidId>9072d421-1967-4523-8611-2b56d6afe9ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WorkCenterMaintenancePlantCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WorkCenterMaintenancePlantCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bad9e887-827d-4d1e-bf32-da01cfac7e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61017fed-0c28-4b1d-ac46-f3402b6d31bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d005177c-d68a-4da7-9a8e-f4c66581c3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WorkCenterMaintenancePlantCode</value>
      <webElementGuid>e70e7da8-5188-47eb-8ace-a740de60512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WorkCenterMaintenancePlantCode</value>
      <webElementGuid>54e1f93e-dc2c-41f1-b5a2-72677d22de86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WorkCenterMaintenancePlantCode&quot;)</value>
      <webElementGuid>cd0230ef-9a05-4f64-8002-0e17de15bf52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WorkCenterMaintenancePlantCode']</value>
      <webElementGuid>521ed919-c602-4c35-8f5a-1fdb0c061d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detailsForm']/div[12]/div/input</value>
      <webElementGuid>ebc6644f-42cd-4f93-8190-8ced3d6fea7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>81fdb72a-c12e-4b9d-90e0-45eed2fcc8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'WorkCenterMaintenancePlantCode' and @name = 'WorkCenterMaintenancePlantCode']</value>
      <webElementGuid>826f05fb-fe6b-4961-aeca-66a6bdf74430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
