<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Any Maintenance plantRE01 - Mogalakw_91391d</name>
   <tag></tag>
   <elementGuidId>12dca628-e237-4ff1-abc6-da59e20fff58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SelectedMaintenancePlantsID1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedMaintenancePlantsID1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ed4b9f3-ac52-454c-b316-3214f11f0cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-chosen form-control</value>
      <webElementGuid>8e242ddc-7ab7-42d2-b5a9-720e520e08bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectedMaintenancePlantsID1</value>
      <webElementGuid>3adeae65-9e7c-43e7-ae33-3f28fc7fd5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectedMaintenancePlantsID1</value>
      <webElementGuid>0cfdf135-a905-4197-be40-8348aa905772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Any Maintenance plantRE01 - Mogalakwena Central ServicesRE10 - Mogalakwena South ConcentratorRE11 - Mogalakwena North ConcentratorRE12 - Mogalakwena Concentrator 3RE20 - Mogalakwena Engineering Open CRE21 - Mogalakwena DeclinesRE30 - Mogalakwena Open CastREC0 - Mogalakwena ComplexRED0 - Twickenham ComplexRED0 - Twickenham ComplexRED2 - Twickenham Mine 1 HackneyRED3 - Twickenham Mine 2 TwickenhamRED4 - Twickenham Central ServicesREE0 - Der Brochen ComplexREE0 - Der Brochen ComplexREG0 - Polokwane Smelter ComplexREG0 - Polokwane Smelter ComplexREG1 - Eastern Limb Bushveld LabREG2 - Polokwane SmelterREJ0 - Mototolo ComplexREJ0 - Mototolo ComplexREJ1 - Mototolo ConcentratorREJ2 - BorwaREJ3 - LebowaREJ4 - Der Brochen NorthREJ5 - Der Brochen SouthREJ9 - Mototolo Central LogisticsRP00 - Precious Metals RefinersRP01 - PMR Level 1RP02 - PMR Level 2RP03 - PMR Level 3RPA0 - Waterval SmelterRPA0 - Waterval SmelterRPA1 - Waterval SmelterRPB0 - Anglo Converter PlantRPB0 - Anglo Converter PlantRPB1 - Acid PlantRPB2 - DML LabRPB3 - Converter PlantRPC0 - Rtb Base Metals RefinersRPC0 - Rtb Base Metals RefinersRPC1 - MPCRPC2 - BMRRPD0 - Precious Metals RefinersRPD0 - Precious Metals RefinersRSW0 - Western Limb DCRSW0 - Western Limb DCRSW1 - Western Limb DCRW01 - Amandelbult Central ServicesRW05 - Amandelbult UG2#1RW10 - Amandelbult UG2#2RW15 - Amandelbult MerenskyRW20 - Dishaba LowerRW25 - Dishaba UpperRW30 - Tumela UpperRW35 - Tumela LowerRW40 - Amandelbult OpencastRW45 - Amandelbult Concentrator ServiRW50 - Amandelbult Properties &amp; FacilRWB0 - Amandelbult ComplexRWB0 - Amandelbult ComplexRWC0 - Mortimer SmelterRWC0 - Mortimer SmelterRWC1 - Mortimer SmelterRWD0 - Rustenburg CentralRWD0 - Rustenburg CentralRWD1 - Process Division Services</value>
      <webElementGuid>436e8fdb-78d8-480d-b5e7-b869e1f1f9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedMaintenancePlantsID1&quot;)</value>
      <webElementGuid>75df75bb-b13c-4161-8772-97e26ac5156a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SelectedMaintenancePlantsID1']</value>
      <webElementGuid>cadd4e79-d4a2-486b-967a-87ed9ff83127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detailsForm']/div[3]/div/select</value>
      <webElementGuid>de914cf2-5613-4804-8da5-d34550708110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance plant'])[3]/following::select[1]</value>
      <webElementGuid>cdeac0d7-1182-4934-b1cf-4e7e248ad42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Codes'])[2]/following::select[2]</value>
      <webElementGuid>6a7cebeb-36e3-4d26-b304-070679282296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Location'])[2]/preceding::select[1]</value>
      <webElementGuid>57ff0117-9705-4e8c-8a39-5ffec5620931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/preceding::select[1]</value>
      <webElementGuid>1262d6b7-7b07-4e03-9255-f60fcc74ae15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>00df39fa-815d-4a9a-a8de-1ee7f94caf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SelectedMaintenancePlantsID1' and @name = 'SelectedMaintenancePlantsID1' and (text() = 'Any Maintenance plantRE01 - Mogalakwena Central ServicesRE10 - Mogalakwena South ConcentratorRE11 - Mogalakwena North ConcentratorRE12 - Mogalakwena Concentrator 3RE20 - Mogalakwena Engineering Open CRE21 - Mogalakwena DeclinesRE30 - Mogalakwena Open CastREC0 - Mogalakwena ComplexRED0 - Twickenham ComplexRED0 - Twickenham ComplexRED2 - Twickenham Mine 1 HackneyRED3 - Twickenham Mine 2 TwickenhamRED4 - Twickenham Central ServicesREE0 - Der Brochen ComplexREE0 - Der Brochen ComplexREG0 - Polokwane Smelter ComplexREG0 - Polokwane Smelter ComplexREG1 - Eastern Limb Bushveld LabREG2 - Polokwane SmelterREJ0 - Mototolo ComplexREJ0 - Mototolo ComplexREJ1 - Mototolo ConcentratorREJ2 - BorwaREJ3 - LebowaREJ4 - Der Brochen NorthREJ5 - Der Brochen SouthREJ9 - Mototolo Central LogisticsRP00 - Precious Metals RefinersRP01 - PMR Level 1RP02 - PMR Level 2RP03 - PMR Level 3RPA0 - Waterval SmelterRPA0 - Waterval SmelterRPA1 - Waterval SmelterRPB0 - Anglo Converter PlantRPB0 - Anglo Converter PlantRPB1 - Acid PlantRPB2 - DML LabRPB3 - Converter PlantRPC0 - Rtb Base Metals RefinersRPC0 - Rtb Base Metals RefinersRPC1 - MPCRPC2 - BMRRPD0 - Precious Metals RefinersRPD0 - Precious Metals RefinersRSW0 - Western Limb DCRSW0 - Western Limb DCRSW1 - Western Limb DCRW01 - Amandelbult Central ServicesRW05 - Amandelbult UG2#1RW10 - Amandelbult UG2#2RW15 - Amandelbult MerenskyRW20 - Dishaba LowerRW25 - Dishaba UpperRW30 - Tumela UpperRW35 - Tumela LowerRW40 - Amandelbult OpencastRW45 - Amandelbult Concentrator ServiRW50 - Amandelbult Properties &amp; FacilRWB0 - Amandelbult ComplexRWB0 - Amandelbult ComplexRWC0 - Mortimer SmelterRWC0 - Mortimer SmelterRWC1 - Mortimer SmelterRWD0 - Rustenburg CentralRWD0 - Rustenburg CentralRWD1 - Process Division Services' or . = 'Any Maintenance plantRE01 - Mogalakwena Central ServicesRE10 - Mogalakwena South ConcentratorRE11 - Mogalakwena North ConcentratorRE12 - Mogalakwena Concentrator 3RE20 - Mogalakwena Engineering Open CRE21 - Mogalakwena DeclinesRE30 - Mogalakwena Open CastREC0 - Mogalakwena ComplexRED0 - Twickenham ComplexRED0 - Twickenham ComplexRED2 - Twickenham Mine 1 HackneyRED3 - Twickenham Mine 2 TwickenhamRED4 - Twickenham Central ServicesREE0 - Der Brochen ComplexREE0 - Der Brochen ComplexREG0 - Polokwane Smelter ComplexREG0 - Polokwane Smelter ComplexREG1 - Eastern Limb Bushveld LabREG2 - Polokwane SmelterREJ0 - Mototolo ComplexREJ0 - Mototolo ComplexREJ1 - Mototolo ConcentratorREJ2 - BorwaREJ3 - LebowaREJ4 - Der Brochen NorthREJ5 - Der Brochen SouthREJ9 - Mototolo Central LogisticsRP00 - Precious Metals RefinersRP01 - PMR Level 1RP02 - PMR Level 2RP03 - PMR Level 3RPA0 - Waterval SmelterRPA0 - Waterval SmelterRPA1 - Waterval SmelterRPB0 - Anglo Converter PlantRPB0 - Anglo Converter PlantRPB1 - Acid PlantRPB2 - DML LabRPB3 - Converter PlantRPC0 - Rtb Base Metals RefinersRPC0 - Rtb Base Metals RefinersRPC1 - MPCRPC2 - BMRRPD0 - Precious Metals RefinersRPD0 - Precious Metals RefinersRSW0 - Western Limb DCRSW0 - Western Limb DCRSW1 - Western Limb DCRW01 - Amandelbult Central ServicesRW05 - Amandelbult UG2#1RW10 - Amandelbult UG2#2RW15 - Amandelbult MerenskyRW20 - Dishaba LowerRW25 - Dishaba UpperRW30 - Tumela UpperRW35 - Tumela LowerRW40 - Amandelbult OpencastRW45 - Amandelbult Concentrator ServiRW50 - Amandelbult Properties &amp; FacilRWB0 - Amandelbult ComplexRWB0 - Amandelbult ComplexRWC0 - Mortimer SmelterRWC0 - Mortimer SmelterRWC1 - Mortimer SmelterRWD0 - Rustenburg CentralRWD0 - Rustenburg CentralRWD1 - Process Division Services')]</value>
      <webElementGuid>7e829eb3-1f95-4c64-8181-9643365f1d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
