<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Any Company CodeR000 - Rustenburg Pl_53402a</name>
   <tag></tag>
   <elementGuidId>1ea3b8f4-ce91-479a-a4cc-4ea32357c227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SelectedCompanyCodesID1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedCompanyCodesID1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>68e6e029-47a9-44fb-b861-30a8882e5456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-chosen form-control</value>
      <webElementGuid>69181dc6-efb2-41d0-bdff-630d393e34ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectedCompanyCodesID1</value>
      <webElementGuid>85368717-cb34-4948-bad9-147468c80d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectedCompanyCodesID1</value>
      <webElementGuid>e249181b-76f2-4655-87ba-034484f4de37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Any Company CodeR000 - Rustenburg Platinum Mines LimtedR102 - Modikwa Platinum MineR149 - Modikwa JV EntriesR150 - Kroondal &amp; Marikana PSAR151 - The Work Expert Pty LtdR202 - Anglo Platinum Marketing Limited - UKR203 - APML - Adjustment EntityR204 - Anglo Platinum Marketing Limited - SGPR323 - Modikwa Platinum Mine PTYR324 - Modikwa Mining Personnel Services Pty LtdR325 - Matthey Rustenburg Refiners Pty LtdR332 - Unki Mines Private LimitedR333 - Amzim Holdings LimitedR334 - Erabas B.VR345 - Southridge LimitedR355 - Atomatic Trading (Pty) LtdR399 - MMPS 50% AdjustmentR420 - PGI S.A.R422 - Platinum Guild International K.K.R423 - Platinum Guild International Hong Kong LimitedR425 - Platinum Guild International (U.S.A.) Jewelry, Inc.R426 - Platinum Guild India Private LimitedR427 - Platinum Guild International (Shangahai) Co., LtdR502 - Lexshell 49 General Trading Pty LtdR600 - The Platinum Producers' Environmental TrustR603 - RPM ESOP TrustR604 - Unki ESOP TrustR700 - Platmed (Pty) LtdR705 - Platmed Properties (Pty) Ltd</value>
      <webElementGuid>9c9fff47-9fa0-4ea5-8487-51d35f9ba91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedCompanyCodesID1&quot;)</value>
      <webElementGuid>d27a2fb8-29bc-4000-95c6-a4397b3670f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SelectedCompanyCodesID1']</value>
      <webElementGuid>3cac34b1-0d0d-4f17-b306-edbb0580fe20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detailsForm']/div[2]/div/select</value>
      <webElementGuid>83794251-5be8-46e6-b41a-e6028faac041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Codes'])[2]/following::select[1]</value>
      <webElementGuid>1f38974e-abc3-4c01-a9d4-540255761a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[2]/following::select[2]</value>
      <webElementGuid>9b88bbdd-bf18-4be8-a6b9-5429bb49b228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance plant'])[3]/preceding::select[1]</value>
      <webElementGuid>cb399d71-9833-4cf1-ba3b-4098cc995bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Location'])[2]/preceding::select[2]</value>
      <webElementGuid>9aa83dfd-93fe-49a2-9c42-84fec1b3ce93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>6ce147db-7a7c-418d-b261-d85527d2a919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SelectedCompanyCodesID1' and @name = 'SelectedCompanyCodesID1' and (text() = concat(&quot;Any Company CodeR000 - Rustenburg Platinum Mines LimtedR102 - Modikwa Platinum MineR149 - Modikwa JV EntriesR150 - Kroondal &amp; Marikana PSAR151 - The Work Expert Pty LtdR202 - Anglo Platinum Marketing Limited - UKR203 - APML - Adjustment EntityR204 - Anglo Platinum Marketing Limited - SGPR323 - Modikwa Platinum Mine PTYR324 - Modikwa Mining Personnel Services Pty LtdR325 - Matthey Rustenburg Refiners Pty LtdR332 - Unki Mines Private LimitedR333 - Amzim Holdings LimitedR334 - Erabas B.VR345 - Southridge LimitedR355 - Atomatic Trading (Pty) LtdR399 - MMPS 50% AdjustmentR420 - PGI S.A.R422 - Platinum Guild International K.K.R423 - Platinum Guild International Hong Kong LimitedR425 - Platinum Guild International (U.S.A.) Jewelry, Inc.R426 - Platinum Guild India Private LimitedR427 - Platinum Guild International (Shangahai) Co., LtdR502 - Lexshell 49 General Trading Pty LtdR600 - The Platinum Producers&quot; , &quot;'&quot; , &quot; Environmental TrustR603 - RPM ESOP TrustR604 - Unki ESOP TrustR700 - Platmed (Pty) LtdR705 - Platmed Properties (Pty) Ltd&quot;) or . = concat(&quot;Any Company CodeR000 - Rustenburg Platinum Mines LimtedR102 - Modikwa Platinum MineR149 - Modikwa JV EntriesR150 - Kroondal &amp; Marikana PSAR151 - The Work Expert Pty LtdR202 - Anglo Platinum Marketing Limited - UKR203 - APML - Adjustment EntityR204 - Anglo Platinum Marketing Limited - SGPR323 - Modikwa Platinum Mine PTYR324 - Modikwa Mining Personnel Services Pty LtdR325 - Matthey Rustenburg Refiners Pty LtdR332 - Unki Mines Private LimitedR333 - Amzim Holdings LimitedR334 - Erabas B.VR345 - Southridge LimitedR355 - Atomatic Trading (Pty) LtdR399 - MMPS 50% AdjustmentR420 - PGI S.A.R422 - Platinum Guild International K.K.R423 - Platinum Guild International Hong Kong LimitedR425 - Platinum Guild International (U.S.A.) Jewelry, Inc.R426 - Platinum Guild India Private LimitedR427 - Platinum Guild International (Shangahai) Co., LtdR502 - Lexshell 49 General Trading Pty LtdR600 - The Platinum Producers&quot; , &quot;'&quot; , &quot; Environmental TrustR603 - RPM ESOP TrustR604 - Unki ESOP TrustR700 - Platmed (Pty) LtdR705 - Platmed Properties (Pty) Ltd&quot;))]</value>
      <webElementGuid>692135f3-0b12-4d80-9acc-c612e5737b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
