<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>approvalComment3</name>
   <tag></tag>
   <elementGuidId>cc539b5e-2b09-45be-b436-fd3214da009e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d4779e28-e02b-4c61-b3aa-b50e79ec0f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f4157b8-277b-489e-aa4e-610974d2fed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>375e4f3f-32ce-44aa-a29e-f4c8c6cc6012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 w-100 form-control rounded-0</value>
      <webElementGuid>3a1e9751-a6a5-42e1-9b51-5af048cc52c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueApprovalBulk&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column px-0&quot;]/div[@class=&quot;overflow-auto px-3 anglo-scrollbar&quot;]/div[@class=&quot;d-flex flex-column border-bottom&quot;]/div[@class=&quot;d-flex align-items-start w-100 mt-2 pb-2&quot;]/div[@class=&quot;col-6 flex-column align-items-start pr-0&quot;]/div[@class=&quot;col-12 flex-column px-0&quot;]/textarea[@class=&quot;mb-0 w-100 form-control rounded-0&quot;]</value>
      <webElementGuid>39d9f5ae-2a37-4659-82a0-c34a36c432c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[3]</value>
      <webElementGuid>3f27ffc6-e1d3-4bf4-9312-128c7298ffae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueApprovalBulk']/div/div/div/div/div[4]/div/div[2]/div[2]/textarea</value>
      <webElementGuid>d76ee4bf-4ffe-493e-a3ee-fa509eb06eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[2]/textarea</value>
      <webElementGuid>1a173f81-a2ac-45d5-baff-e80dbdaa02ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text']</value>
      <webElementGuid>c5903c44-8d20-4560-9710-6e2cadf0e172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
