<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bulkREJECT</name>
   <tag></tag>
   <elementGuidId>680c1b8c-66f4-440e-8eeb-f73e051fc1e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnCancel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnCancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>151df883-5db6-479c-a8a7-7140b4a6d765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c2cd422-368a-410c-b60f-912a3c5d3e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCancel</value>
      <webElementGuid>df1e1d03-5626-4915-b223-40c491b39e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnCancel</value>
      <webElementGuid>df1fdd65-0935-4c1d-a91d-4ab482076086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary custom-height px-5 font-weight-bold ml-3</value>
      <webElementGuid>bac1eb2f-676c-43a7-bc01-8d89bd1a3d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REJECT</value>
      <webElementGuid>93a788f5-c33c-4db7-a093-8941a346988c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn pb-3&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-lg-12 px-lg-1&quot;]/div[@class=&quot;card h-100 mb-0 rounded-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-horizontal ays-ignore w-100&quot;]/div[@class=&quot;d-none d-sm-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 pb-3 d-flex align-items-end justify-content-end&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;d-flex&quot;]/button[@id=&quot;btnCancel&quot;]</value>
      <webElementGuid>d742d02b-c5e1-43c8-afae-52f52a445791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnCancel']</value>
      <webElementGuid>86136b46-9a68-4765-88eb-50bfec8225eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div[2]/div/div/div/div[2]/div/div/button[2]</value>
      <webElementGuid>ac75b099-aaf0-4166-9046-2ae38ec93324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPROVE'])[1]/following::button[1]</value>
      <webElementGuid>19c8e951-ec2c-4ed7-8e6f-c68739292b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/following::button[2]</value>
      <webElementGuid>1a5e3b0d-9b42-4b45-a963-82d46c695cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Centre'])[2]/preceding::button[1]</value>
      <webElementGuid>ca6ccec3-4cf6-4bae-add0-bbc22e092100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TL - TUMELA LOWER SEM (MAIN)'])[1]/preceding::button[1]</value>
      <webElementGuid>32e6f51b-8027-41e1-b5fc-fdce26d69567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REJECT']/parent::*</value>
      <webElementGuid>78356e4f-3522-40e8-b92a-3b1a0ab48239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/button[2]</value>
      <webElementGuid>34b00308-1f05-4d53-9d8c-70ea1cce6140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnCancel' and @name = 'btnCancel' and (text() = 'REJECT' or . = 'REJECT')]</value>
      <webElementGuid>d81345a6-6993-4af6-83e7-328cbfb91c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
