<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CLOSE</name>
   <tag></tag>
   <elementGuidId>50af72ec-555c-485e-ab28-d2853395bd87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closebutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closebutton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b98497ac-2558-4f32-b550-e6673f78d968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closebutton</value>
      <webElementGuid>b87a5561-503b-416b-9c78-054e1cbb1b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f7246081-a0ee-40b9-92f6-995f92a31aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary px-5 font-weight-bold</value>
      <webElementGuid>7c5a58d6-8576-477e-8e13-aeb27f787caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>c5ed8bca-4841-4d32-b493-d8c08e6a8b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closebutton&quot;)</value>
      <webElementGuid>f284d035-7227-4bbc-95b6-8bed82983b7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closebutton']</value>
      <webElementGuid>ba3ea671-8163-4792-9186-792881ff2828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueApprovalSingleContainer']/div/div/div/div[5]/button[2]</value>
      <webElementGuid>41ee903a-5d68-4d7d-b24a-00698c5d8385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE'])[1]/following::button[1]</value>
      <webElementGuid>54acfb0a-8741-4797-9495-576cfa8755fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order No ()'])[1]/following::button[2]</value>
      <webElementGuid>61f436f7-7d11-424a-ba1e-de28fa60de5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/preceding::button[1]</value>
      <webElementGuid>9a665523-9f38-446e-b81e-dd453c838df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Form'])[1]/preceding::button[2]</value>
      <webElementGuid>bc4ec051-2d7b-4dc4-94f0-0261f1112d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLOSE']/parent::*</value>
      <webElementGuid>818c7080-a820-40da-8ae4-b15630181b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button[2]</value>
      <webElementGuid>69d7ea9b-da24-45a8-81b8-e458eadbb908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closebutton' and (text() = 'CLOSE' or . = 'CLOSE')]</value>
      <webElementGuid>f549c621-6cc5-41fd-8ead-1540d5da6482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
