<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Home_nav-icon icon-home aa-primary</name>
   <tag></tag>
   <elementGuidId>c1c52dcf-f500-4568-9123-110d7a99e64f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.nav-icon.icon-home.aa-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='sidebar-nav-id']/ul/li/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b4ddb352-1fda-4030-8a20-f60595641928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-icon icon-home aa-primary</value>
      <webElementGuid>bc022b6a-bcb1-46f9-8f4d-19ff923e5c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav-id&quot;)/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item nav-dropdown&quot;]/a[@class=&quot;nav-link w-100 aa-primary&quot;]/i[@class=&quot;nav-icon icon-home aa-primary&quot;]</value>
      <webElementGuid>682a94ef-aa28-4a18-9086-fe0181f476a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='sidebar-nav-id']/ul/li/a/i</value>
      <webElementGuid>34fd0682-66ea-4610-99e4-34aa33fe65e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a/i</value>
      <webElementGuid>0980be65-df0f-4abc-b8b5-dc7d0ae4f725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
