<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1567f9d9-d514-4a73-bb90-53a02ceb6e45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-header.bg-white.d-flex.py-2.justify-content-between > button.close.aa-primary > img[alt=&quot;Close&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='singleApprovalModal']/div/div/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>72e6a086-d69f-47e9-8c21-48e61f37a906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/close.svg</value>
      <webElementGuid>61ea0811-bf8d-492c-8e4b-86038b5bc858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>20fa36e9-267f-49f3-8c45-c4ddcb60f142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>97d7b419-5ec2-492a-bc17-0b8ac694f6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>3ad491a5-59f1-4968-a0e6-f0fd04f72f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;singleApprovalModal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content rounded-0&quot;]/div[@class=&quot;modal-header bg-white d-flex py-2 justify-content-between&quot;]/button[@class=&quot;close aa-primary&quot;]/img[1]</value>
      <webElementGuid>84aa2a4c-3c9c-4d94-8e79-bb9319ce626e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singleApprovalModal']/div/div/div/button/img</value>
      <webElementGuid>62dafeeb-720e-4135-8441-5fbffd150072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Close'])[2]</value>
      <webElementGuid>cf8476e9-3ccc-4efd-bbde-b56666619d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button/img</value>
      <webElementGuid>8241f194-1298-4ac7-93f5-c03459f535d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/close.svg' and @alt = 'Close']</value>
      <webElementGuid>73484943-8123-45c8-a209-367796bdeec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
