<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upper cost limit_uppercost</name>
   <tag></tag>
   <elementGuidId>b2e8020f-8071-44e2-b87b-a995e84a5ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uppercost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uppercost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>113990f8-bc7e-4899-a59e-f27428f69914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>80b000c1-1942-4117-8803-3bad29d23e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uppercost</value>
      <webElementGuid>90069c99-25e9-4286-abb6-027d0518efae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uppercost</value>
      <webElementGuid>0194170a-c78a-42f1-964d-9f7c586da7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6deaa7e3-1f5c-46f5-900f-e6d734f503ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>120d4764-48c1-424d-9f90-fc791598edb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>3bdcb852-f21b-4deb-a298-83d5f7f22999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 form-control rounded-0</value>
      <webElementGuid>fe597c58-3cc2-4339-a15c-fdd55c5eef16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uppercost&quot;)</value>
      <webElementGuid>7e6e9b9b-f6a1-441a-8663-914bdec4d395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uppercost']</value>
      <webElementGuid>3eaa25aa-44c7-4213-9f61-ad95782cd2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueApprovalSingleContainer']/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>9ebb3f18-c85e-4ab1-9754-0f16b4903278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>2b158f56-8f74-4be3-82f4-bc32d18492c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'uppercost' and @name = 'uppercost']</value>
      <webElementGuid>421dcfa1-5353-42c4-b41d-a31c89c168eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
