<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add to long description_addtolongdescription</name>
   <tag></tag>
   <elementGuidId>e78046c3-2aec-41fb-b28c-0d19432dfe3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addtolongdescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addtolongdescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaf2aebb-bf7a-4b25-b94b-e7ecf16e981e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>287d3ed6-6719-4c30-9dde-9cfbf8947efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2080</value>
      <webElementGuid>97521e63-0e69-4fad-a537-73268b7dfabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addtolongdescription</value>
      <webElementGuid>878d1f55-401c-4fae-bb03-115f2ced52c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtolongdescription</value>
      <webElementGuid>58101d9a-22d4-43dd-b3b0-b41f504daad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6bcab6e-1f68-4b5f-b996-904f4a65f1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 form-control round form-control-sm mb-0 left-modal-text inpusize rounded-0</value>
      <webElementGuid>a794d284-7679-4e79-8b70-505dedfa4269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addtolongdescription&quot;)</value>
      <webElementGuid>9eb62ded-79a8-4491-8e0c-9473c7f8706d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addtolongdescription']</value>
      <webElementGuid>cbf12bf9-f812-45f0-9dba-ef75c75692dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info']/div/div[28]/div[2]/input</value>
      <webElementGuid>b46656a7-1ea6-43b3-b57f-0c759988d96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div[2]/input</value>
      <webElementGuid>2655afe5-4e2a-4b2a-9b49-00916d3ee2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'addtolongdescription' and @name = 'addtolongdescription']</value>
      <webElementGuid>6246b7f5-6c15-4452-8366-28611cefce86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
