<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rejectionComment3</name>
   <tag></tag>
   <elementGuidId>e7f4fb07-3f7b-4fee-88a9-270bb2c7c2ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3f7ed023-5aeb-4fcd-b84b-43fa6893c920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>405ea80c-e4cb-4fa9-9205-b855719b6528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7fd9e334-56ac-4b41-a248-45473478c4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 w-100 form-control rounded-0</value>
      <webElementGuid>2e9cdf8e-da1b-4e5d-beb0-cfc150a209fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueApprovalBulk&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column px-0&quot;]/div[@class=&quot;overflow-auto px-3 anglo-scrollbar&quot;]/div[@class=&quot;d-flex flex-column border-bottom&quot;]/div[@class=&quot;d-flex align-items-start w-100 mt-2 pb-2&quot;]/div[@class=&quot;col-6 flex-column align-items-start pr-0&quot;]/div[@class=&quot;col-12 flex-column px-0&quot;]/textarea[@class=&quot;mb-0 w-100 form-control rounded-0&quot;]</value>
      <webElementGuid>13c90a0c-82c2-45e1-aab1-3aad0d7fff86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[3]</value>
      <webElementGuid>cc329b37-7172-4a75-b8f4-3057499a20b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueApprovalBulk']/div/div/div/div/div[4]/div/div[2]/div/textarea</value>
      <webElementGuid>d9f64e39-007c-4994-af62-11537e734150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/textarea</value>
      <webElementGuid>d0f9ff64-c1b0-42ae-9ada-6efa82f94f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text']</value>
      <webElementGuid>4cad7424-4017-4d0f-a8c0-20d09ecc8000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
