<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_314012</name>
   <tag></tag>
   <elementGuidId>172093f3-e2e4-4144-98d9-22756e7e07f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.tabletd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div/div/div[3]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e288a106-3b2d-4ea1-b218-b02e5428e398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabletd</value>
      <webElementGuid>94fd77ab-0398-4047-b328-aa75ddaa89ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>314012</value>
      <webElementGuid>57450c75-a7d2-435c-a995-72fba280466c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;col&quot;]/div[@class=&quot;card mr-lg-4 ml-lg-3 rounded-0&quot;]/div[@class=&quot;card-body ml-3 mr-3&quot;]/div[@class=&quot;row mt-4 measurementTable&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[@class=&quot;cursorPointer&quot;]/td[@class=&quot;tabletd&quot;]</value>
      <webElementGuid>5fa35414-b878-477b-9ac9-13ad5377c99d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/div/div[3]/table/tbody/tr/td</value>
      <webElementGuid>fc88996c-2abb-4e9e-bdf3-13fcaf9f6351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Counter'])[1]/following::td[1]</value>
      <webElementGuid>d0f2ac6b-39ff-42bc-ac63-f14245f5291d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit of measure'])[1]/following::td[1]</value>
      <webElementGuid>259fb746-6d3e-4a0d-9791-180c82657027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::td[1]</value>
      <webElementGuid>2858c07d-269f-451e-8e15-a70515037d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kilometer'])[1]/preceding::td[2]</value>
      <webElementGuid>1af63c81-2006-4a0d-a992-586cb85a68e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='314012']/parent::*</value>
      <webElementGuid>be610441-df04-41f4-8116-a00597018766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>1e5e6f81-611d-48be-8e13-da58f59f92e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '314012' or . = '314012')]</value>
      <webElementGuid>72414853-bebd-4e3a-96ff-a4f1d1172503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
