<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uppercost2</name>
   <tag></tag>
   <elementGuidId>f6de459e-80b2-4933-a504-21e165bf0eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c88968ce-6d79-4888-bb17-342ec6812c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a10b8461-9420-4656-a853-c91d0010768e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8ce06cde-6ae6-44bc-9436-d8e43997379b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 w-100 form-control rounded-0</value>
      <webElementGuid>be216091-21e6-47a4-9d87-e4c94ae5d958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueApprovalBulk&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column px-0&quot;]/div[@class=&quot;overflow-auto px-3 anglo-scrollbar&quot;]/div[@class=&quot;d-flex flex-column border-bottom&quot;]/div[@class=&quot;d-flex align-items-start w-100 mt-2 pb-2&quot;]/div[@class=&quot;col-6 flex-column align-items-start pr-0&quot;]/div[@class=&quot;col-12 flex-column mb-3 px-0&quot;]/input[@class=&quot;mb-0 w-100 form-control rounded-0&quot;]</value>
      <webElementGuid>93bb1554-8362-46e3-a976-f6e69868acb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[2]</value>
      <webElementGuid>34c598d0-3376-4a90-85da-ed8a67a21e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueApprovalBulk']/div/div/div/div/div[3]/div/div[2]/div/input</value>
      <webElementGuid>f1ff8ed3-48f3-4bbd-ad0d-f0aac398dc6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>2eca2d11-4d54-4f6b-8c5e-c8ea5b0ae0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>6daccc79-5e02-4146-9ba3-ea0b5ea99808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
