<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT_1_2</name>
   <tag></tag>
   <elementGuidId>c006762f-a704-48b4-9cf7-81139157a436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nextbtndescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nextbtndescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71963bb7-2842-44ae-b001-75f6a3472348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4df75108-050f-4864-9ab0-8e0ac2e5ef1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next btn btn-primary px-5 font-weight-bold</value>
      <webElementGuid>2d8505b2-e65d-4e4d-8d52-dbd05360c26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextbtndescription</value>
      <webElementGuid>1c0809ea-e5e6-42d3-b8d6-a49b3c84d0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>004f6031-1374-48c0-a247-a624cb716c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextbtndescription&quot;)</value>
      <webElementGuid>e74dfc32-90d4-4865-a127-d21b92f4650d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nextbtndescription']</value>
      <webElementGuid>3172c088-5ef7-47f5-b712-8dff48d35cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>0b5af677-e86b-4f32-9990-7d775744a44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK'])[1]/following::button[1]</value>
      <webElementGuid>c11bb084-68e2-49af-adc5-ce90b59e4aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload a photo'])[1]/following::button[2]</value>
      <webElementGuid>6ad2a261-62c0-4a7a-8ff7-691689d0f472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit_Booking'])[1]/preceding::button[1]</value>
      <webElementGuid>629618c8-67d4-4850-8f11-96742bad5ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Request'])[2]/preceding::button[2]</value>
      <webElementGuid>e67d4c36-99d5-4e60-b098-2ce830f36f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT']/parent::*</value>
      <webElementGuid>2710bdaf-7bc0-4723-b6e1-e0a085885b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button</value>
      <webElementGuid>6b3b02f6-f674-4ee1-a169-5264ede2f847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nextbtndescription' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>ca36a9ef-8570-4a7f-bad7-c11450817fa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
