<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Required date_fa fa-calendar</name>
   <tag></tag>
   <elementGuidId>e06872fe-12f7-4ce5-a9a8-9ff305c09ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/label/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d851ce11-9803-42c9-afe0-66222927ca95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
      <webElementGuid>19b8131f-49ba-49e3-a548-67d16c411132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppContainer1&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;flex-column px-3 justify-content-start align-items-start&quot;]/div[@class=&quot;d-flex col-8 pl-0 align-items-center mt-1 aa-outlines-blue&quot;]/label[@class=&quot;date-icon d-flex align-items-center pr-2 mb-0&quot;]/i[@class=&quot;fa fa-calendar&quot;]</value>
      <webElementGuid>ebe922a6-ba3f-4fcf-be20-96061ce60813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/label/i</value>
      <webElementGuid>dcd516cf-e8eb-4682-b2b4-c4fafedb3d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
      <webElementGuid>5104c32a-ac81-4efd-a19d-e295e018e4c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
