<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tumela Lower 1 Shaft UG_mr-2 border-left pl-2</name>
   <tag></tag>
   <elementGuidId>87e9b14e-c871-46f4-a12f-71ea51def5fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mr-2.border-left.pl-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>18e05c44-6419-4c98-9cb8-ca6a933680f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png</value>
      <webElementGuid>85b2aa4c-8d9b-4476-8173-e9b44af05847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e31ea01f-f08b-4de9-bf2f-8e73ffdd2848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 border-left pl-2</value>
      <webElementGuid>9f446d8c-455b-4c05-bbfb-dcd5cebcb58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppContainer1&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;overflow-auto ml-2 mr-2 anglo-scrollbar&quot;]/div[1]/div[@class=&quot;d-flex wiz-list-item c-pointer py-2 border-bottom&quot;]/div[@class=&quot;d-flex align-self-center w-50 justify-content-end&quot;]/img[@class=&quot;mr-2 border-left pl-2&quot;]</value>
      <webElementGuid>34a1e1df-b789-45e4-981a-94fc753edb39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      <webElementGuid>4176b23c-9095-4a51-902b-6d910b16dcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png')]</value>
      <webElementGuid>6f788284-aa25-479d-9c62-65b5315e7f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>ea0ab693-b38d-44b9-adb8-b4ad05397b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png']</value>
      <webElementGuid>dbe21b13-e3f1-4574-bf12-7885a9d71177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
