<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GKEST - MAIN G01</name>
   <tag></tag>
   <elementGuidId>30c2c2d6-a2db-4d4b-b25d-ec9b34658987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='be4b011a-a825-4bb2-a8b6-88caf46a35f5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#be4b011a-a825-4bb2-a8b6-88caf46a35f5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ea0e153-df29-4afe-b359-6f2190f01dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>be4b011a-a825-4bb2-a8b6-88caf46a35f5</value>
      <webElementGuid>40583bf1-ad68-42dc-9849-abe08daf07aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex justify-content-between aa-primary</value>
      <webElementGuid>5139770e-11b7-405a-88d0-9683a3b01635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GKEST - MAIN G01</value>
      <webElementGuid>0f22d772-d34d-443f-a178-63c9c45416e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be4b011a-a825-4bb2-a8b6-88caf46a35f5&quot;)</value>
      <webElementGuid>167aa832-cae0-4fa8-b8ea-8d23835de1f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='be4b011a-a825-4bb2-a8b6-88caf46a35f5']</value>
      <webElementGuid>0032bdcd-527c-46ea-94fc-99c1427b0b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div[4]/div/div</value>
      <webElementGuid>d290f88b-82a3-47bd-8495-e7349f69450e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gahcho Kué Contractors'])[1]/following::div[3]</value>
      <webElementGuid>5c0ad9e3-ca84-4449-9e88-925d08b759cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G01'])[3]/following::div[3]</value>
      <webElementGuid>fd8913ac-f132-407f-83cc-ad545208c4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div</value>
      <webElementGuid>3a5e16bf-5352-4f7d-b8b4-7eaf84be57a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'be4b011a-a825-4bb2-a8b6-88caf46a35f5' and (text() = 'GKEST - MAIN G01' or . = 'GKEST - MAIN G01')]</value>
      <webElementGuid>de262f87-ea71-4f36-8708-3286d16767d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
