<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Required date_fa fa-calendar</name>
   <tag></tag>
   <elementGuidId>55cd9e59-59bc-4fe0-bf0a-ad42158fbfb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/label/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>763735f5-a1d6-4cea-97f9-ffa09f10e7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
      <webElementGuid>5365643a-4e1d-46fb-867b-a7fbe76af8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppContainer1&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;flex-column px-3 justify-content-start align-items-start&quot;]/div[@class=&quot;d-flex col-8 pl-0 align-items-center mt-1 aa-outlines-blue&quot;]/label[@class=&quot;date-icon d-flex align-items-center pr-2 mb-0&quot;]/i[@class=&quot;fa fa-calendar&quot;]</value>
      <webElementGuid>8e904685-b4eb-498c-b908-101b99fc932d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/label/i</value>
      <webElementGuid>5d0b115f-0d6d-4a7b-8731-30521069fba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
      <webElementGuid>74a4ff47-8fd6-4c6f-aa3d-adf12beda9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
