<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CA-GK_mr-2 border-left pl-2</name>
   <tag></tag>
   <elementGuidId>09f1233c-5a67-4ce5-94f7-2aaa75f7bb01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mr-2.border-left.pl-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>973c291e-a8a9-4955-9d73-25c1703c304b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png</value>
      <webElementGuid>3075c259-641a-4962-92d7-4dbd19ad159d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>0fb76a05-f573-40b8-b453-624462d173c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 border-left pl-2</value>
      <webElementGuid>bd5034e1-77e3-4c49-ad38-4c814e096821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppContainer1&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;overflow-auto ml-2 mr-2 anglo-scrollbar&quot;]/div[1]/div[@class=&quot;d-flex wiz-list-item c-pointer py-2&quot;]/div[@class=&quot;d-flex align-self-center w-50 justify-content-end&quot;]/img[@class=&quot;mr-2 border-left pl-2&quot;]</value>
      <webElementGuid>8eacd55d-88ca-40d6-b90c-a222a6c5374b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      <webElementGuid>e818f7eb-41c6-418b-9c34-19815cc8f71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png')]</value>
      <webElementGuid>d57b8930-0d36-4ce6-9141-c81a87f50e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>be848655-cd82-45f6-87d2-0ba392fb8392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png']</value>
      <webElementGuid>bf11fce2-7511-437e-afe8-16237cae9763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
