<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Malfunction start date and time_date</name>
   <tag></tag>
   <elementGuidId>6c5a5a6c-d85f-46d9-b987-c81c2ce3a66b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#malfunctionStartDateTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='malfunctionStartDateTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2965dda9-1077-4b1d-aee5-b6ba9b979371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a9d1f88-1629-4e06-924f-39cfa51c4f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-100 rounded-0 border-right-0</value>
      <webElementGuid>f8ce414d-f28d-4c37-90a1-55ddc7b6b162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4e41061a-33d9-4ee4-b75d-cd5396fed2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>malfunctionStartDateTime</value>
      <webElementGuid>fb72aa74-03d1-438d-8b6b-73fafd82ea32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;malfunctionStartDateTime&quot;)</value>
      <webElementGuid>8b9123b6-c5f2-4f7f-aac6-6a6576a487e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='malfunctionStartDateTime']</value>
      <webElementGuid>1644db11-0872-474b-85e3-748fed7565d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>a54d3fa2-8e10-4e94-aa1f-164f5fdb2c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ef32bdb1-d9ac-4674-a27b-b0fb63f31c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date' and @id = 'malfunctionStartDateTime']</value>
      <webElementGuid>9f65c5d1-15de-4ef5-bf62-92ffaa718558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
