<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Required date_selectedRequiredDate</name>
   <tag></tag>
   <elementGuidId>3b54d4cc-90fb-43d5-9d68-ffd093498b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedRequiredDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedRequiredDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d54c086-57d9-4598-aa66-61cbff348a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbd23baa-1a21-4c37-9f09-dadd07a69cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-100 rounded-0 border-right-0</value>
      <webElementGuid>871d8dc9-9038-4dd3-b1b5-a268e7f782a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedRequiredDate</value>
      <webElementGuid>84a88602-2ccc-417a-95d4-e5df2fb1fbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedRequiredDate&quot;)</value>
      <webElementGuid>f04b1a8b-7bbb-4722-a5b2-669a47227a78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedRequiredDate']</value>
      <webElementGuid>4f521b17-89c3-4469-b319-3aff3fdbfbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>c66375f9-9018-4409-96cb-086553256eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8aa1672f-4630-4f53-b829-3f6cc603d5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectedRequiredDate']</value>
      <webElementGuid>2990ae39-0cd5-46a8-8182-7f08670fbce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
