<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Modified Date_icons font-1xl d-block mt-1_a3c5f0</name>
   <tag></tag>
   <elementGuidId>897185d5-dec7-46a6-9ec4-144d84fde45b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-view']/div/div/div[2]/div/table/tbody/tr/td/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icons.font-1xl.d-block.mt-1.cui-pencil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3217004c-f865-4a1d-bca4-ba8c8edeebf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icons font-1xl d-block mt-1 cui-pencil</value>
      <webElementGuid>2c93c86f-b3c9-487f-8404-6027634a9539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;table-responsive-lg&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[1]/td[1]/button[@class=&quot;btn btn-primary btn-icon btn-sm&quot;]/i[@class=&quot;icons font-1xl d-block mt-1 cui-pencil&quot;]</value>
      <webElementGuid>5911bcfc-ec59-42bc-b476-bbc688bc9f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div[2]/div/table/tbody/tr/td/button/i</value>
      <webElementGuid>28533006-08b5-450f-a627-d599a13b7c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button/i</value>
      <webElementGuid>661f0006-ad1b-474d-ba88-4323dc763eb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
