<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Any Maintenance plantRE01 - Mogalakw_91391d</name>
   <tag></tag>
   <elementGuidId>44fcde9b-176c-448c-a821-777ac274431f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SelectedMaintenancePlantsID1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedMaintenancePlantsID1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>982d436f-3c1d-424d-922f-7d276bf2a570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b0a6bfac-7235-4872-9131-42c90c0e9715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectedMaintenancePlantsID1</value>
      <webElementGuid>facf220b-44fb-4f10-a0aa-0e28436743dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectedMaintenancePlantsID1</value>
      <webElementGuid>7ad3f30b-25f3-4f98-aacc-5f9048d82dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Any Maintenance plantRE01 - Mogalakwena Central ServicesRE10 - Mogalakwena South ConcentratorRE11 - Mogalakwena North ConcentratorRE12 - Mogalakwena Concentrator 3RE20 - Mogalakwena Engineering Open CRE21 - Mogalakwena DeclinesRE30 - Mogalakwena Open CastREC0 - Mogalakwena ComplexRED0 - Twickenham ComplexRED0 - Twickenham ComplexRED2 - Twickenham Mine 1 HackneyRED3 - Twickenham Mine 2 TwickenhamRED4 - Twickenham Central ServicesREE0 - Der Brochen ComplexREE0 - Der Brochen ComplexREG0 - Polokwane Smelter ComplexREG0 - Polokwane Smelter ComplexREG1 - Eastern Limb Bushveld LabREG2 - Polokwane SmelterREJ0 - Mototolo ComplexREJ0 - Mototolo ComplexREJ1 - Mototolo ConcentratorREJ2 - BorwaREJ3 - LebowaREJ4 - Der Brochen NorthREJ5 - Der Brochen SouthREJ9 - Mototolo Central LogisticsRP00 - Precious Metals RefinersRP01 - PMR Level 1RP02 - PMR Level 2RP03 - PMR Level 3RPA0 - Waterval SmelterRPA0 - Waterval SmelterRPA1 - Waterval SmelterRPB0 - Anglo Converter PlantRPB0 - Anglo Converter PlantRPB1 - Acid PlantRPB2 - DML LabRPB3 - Converter PlantRPC0 - Rtb Base Metals RefinersRPC0 - Rtb Base Metals RefinersRPC1 - MPCRPC2 - BMRRPD0 - Precious Metals RefinersRPD0 - Precious Metals RefinersRSW0 - Western Limb DCRSW0 - Western Limb DCRSW1 - Western Limb DCRW01 - Amandelbult Central ServicesRW05 - Amandelbult UG2#1RW10 - Amandelbult UG2#2RW15 - Amandelbult MerenskyRW20 - Dishaba LowerRW25 - Dishaba UpperRW30 - Tumela UpperRW35 - Tumela LowerRW40 - Amandelbult OpencastRW45 - Amandelbult Concentrator ServiRW50 - Amandelbult Properties &amp; FacilRWB0 - Amandelbult ComplexRWB0 - Amandelbult ComplexRWC0 - Mortimer SmelterRWC0 - Mortimer SmelterRWC1 - Mortimer SmelterRWD0 - Rustenburg CentralRWD0 - Rustenburg CentralRWD1 - Process Division Services</value>
      <webElementGuid>dead43b3-45e2-4cc7-88e0-353b7f8a72df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedMaintenancePlantsID1&quot;)</value>
      <webElementGuid>2a62d959-4e29-4494-a231-4e7ad50e55ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SelectedMaintenancePlantsID1']</value>
      <webElementGuid>7930bd7b-b625-4a3b-858f-921984296b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detailsForm']/div[3]/div/select</value>
      <webElementGuid>0edcfc7a-7499-493e-8b97-887bc9c7ad6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance plant'])[3]/following::select[1]</value>
      <webElementGuid>d87dd9a7-da4a-4fe6-9534-7956025f01ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Codes'])[2]/following::select[2]</value>
      <webElementGuid>343ed6e5-28f3-4ec6-86fb-83d33e27ee3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/preceding::select[1]</value>
      <webElementGuid>74713e6f-5916-4643-9f84-8bcc1813c822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/preceding::select[1]</value>
      <webElementGuid>92612f95-9eb0-43f9-8025-0759c6625714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>de847486-e87b-42ad-bc3f-2db56a0602a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SelectedMaintenancePlantsID1' and @name = 'SelectedMaintenancePlantsID1' and (text() = 'Any Maintenance plantRE01 - Mogalakwena Central ServicesRE10 - Mogalakwena South ConcentratorRE11 - Mogalakwena North ConcentratorRE12 - Mogalakwena Concentrator 3RE20 - Mogalakwena Engineering Open CRE21 - Mogalakwena DeclinesRE30 - Mogalakwena Open CastREC0 - Mogalakwena ComplexRED0 - Twickenham ComplexRED0 - Twickenham ComplexRED2 - Twickenham Mine 1 HackneyRED3 - Twickenham Mine 2 TwickenhamRED4 - Twickenham Central ServicesREE0 - Der Brochen ComplexREE0 - Der Brochen ComplexREG0 - Polokwane Smelter ComplexREG0 - Polokwane Smelter ComplexREG1 - Eastern Limb Bushveld LabREG2 - Polokwane SmelterREJ0 - Mototolo ComplexREJ0 - Mototolo ComplexREJ1 - Mototolo ConcentratorREJ2 - BorwaREJ3 - LebowaREJ4 - Der Brochen NorthREJ5 - Der Brochen SouthREJ9 - Mototolo Central LogisticsRP00 - Precious Metals RefinersRP01 - PMR Level 1RP02 - PMR Level 2RP03 - PMR Level 3RPA0 - Waterval SmelterRPA0 - Waterval SmelterRPA1 - Waterval SmelterRPB0 - Anglo Converter PlantRPB0 - Anglo Converter PlantRPB1 - Acid PlantRPB2 - DML LabRPB3 - Converter PlantRPC0 - Rtb Base Metals RefinersRPC0 - Rtb Base Metals RefinersRPC1 - MPCRPC2 - BMRRPD0 - Precious Metals RefinersRPD0 - Precious Metals RefinersRSW0 - Western Limb DCRSW0 - Western Limb DCRSW1 - Western Limb DCRW01 - Amandelbult Central ServicesRW05 - Amandelbult UG2#1RW10 - Amandelbult UG2#2RW15 - Amandelbult MerenskyRW20 - Dishaba LowerRW25 - Dishaba UpperRW30 - Tumela UpperRW35 - Tumela LowerRW40 - Amandelbult OpencastRW45 - Amandelbult Concentrator ServiRW50 - Amandelbult Properties &amp; FacilRWB0 - Amandelbult ComplexRWB0 - Amandelbult ComplexRWC0 - Mortimer SmelterRWC0 - Mortimer SmelterRWC1 - Mortimer SmelterRWD0 - Rustenburg CentralRWD0 - Rustenburg CentralRWD1 - Process Division Services' or . = 'Any Maintenance plantRE01 - Mogalakwena Central ServicesRE10 - Mogalakwena South ConcentratorRE11 - Mogalakwena North ConcentratorRE12 - Mogalakwena Concentrator 3RE20 - Mogalakwena Engineering Open CRE21 - Mogalakwena DeclinesRE30 - Mogalakwena Open CastREC0 - Mogalakwena ComplexRED0 - Twickenham ComplexRED0 - Twickenham ComplexRED2 - Twickenham Mine 1 HackneyRED3 - Twickenham Mine 2 TwickenhamRED4 - Twickenham Central ServicesREE0 - Der Brochen ComplexREE0 - Der Brochen ComplexREG0 - Polokwane Smelter ComplexREG0 - Polokwane Smelter ComplexREG1 - Eastern Limb Bushveld LabREG2 - Polokwane SmelterREJ0 - Mototolo ComplexREJ0 - Mototolo ComplexREJ1 - Mototolo ConcentratorREJ2 - BorwaREJ3 - LebowaREJ4 - Der Brochen NorthREJ5 - Der Brochen SouthREJ9 - Mototolo Central LogisticsRP00 - Precious Metals RefinersRP01 - PMR Level 1RP02 - PMR Level 2RP03 - PMR Level 3RPA0 - Waterval SmelterRPA0 - Waterval SmelterRPA1 - Waterval SmelterRPB0 - Anglo Converter PlantRPB0 - Anglo Converter PlantRPB1 - Acid PlantRPB2 - DML LabRPB3 - Converter PlantRPC0 - Rtb Base Metals RefinersRPC0 - Rtb Base Metals RefinersRPC1 - MPCRPC2 - BMRRPD0 - Precious Metals RefinersRPD0 - Precious Metals RefinersRSW0 - Western Limb DCRSW0 - Western Limb DCRSW1 - Western Limb DCRW01 - Amandelbult Central ServicesRW05 - Amandelbult UG2#1RW10 - Amandelbult UG2#2RW15 - Amandelbult MerenskyRW20 - Dishaba LowerRW25 - Dishaba UpperRW30 - Tumela UpperRW35 - Tumela LowerRW40 - Amandelbult OpencastRW45 - Amandelbult Concentrator ServiRW50 - Amandelbult Properties &amp; FacilRWB0 - Amandelbult ComplexRWB0 - Amandelbult ComplexRWC0 - Mortimer SmelterRWC0 - Mortimer SmelterRWC1 - Mortimer SmelterRWD0 - Rustenburg CentralRWD0 - Rustenburg CentralRWD1 - Process Division Services')]</value>
      <webElementGuid>02c82a46-4669-4c83-baba-7bbfe6e302ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
