<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Any Company CodeR000 - Rustenburg Pl_53402a</name>
   <tag></tag>
   <elementGuidId>7249e5a5-adfb-4fbd-93a2-e9e8f93d42d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SelectedCompanyCodesID1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedCompanyCodesID1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>05ca287e-86c5-4747-9145-099ca3745c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>75dcb602-5825-4774-89fe-1ce490506e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectedCompanyCodesID1</value>
      <webElementGuid>64a9bfb8-2db6-4b96-bcbe-7508fd12ecc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectedCompanyCodesID1</value>
      <webElementGuid>e705a567-05a8-41b7-9fbe-cb3f4a9a590c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Any Company CodeR000 - Rustenburg Platinum Mines LimtedR102 - Modikwa Platinum MineR149 - Modikwa JV EntriesR150 - Kroondal &amp; Marikana PSAR151 - The Work Expert Pty LtdR202 - Anglo Platinum Marketing Limited - UKR203 - APML - Adjustment EntityR204 - Anglo Platinum Marketing Limited - SGPR323 - Modikwa Platinum Mine PTYR324 - Modikwa Mining Personnel Services Pty LtdR325 - Matthey Rustenburg Refiners Pty LtdR332 - Unki Mines Private LimitedR333 - Amzim Holdings LimitedR334 - Erabas B.VR345 - Southridge LimitedR355 - Atomatic Trading (Pty) LtdR399 - MMPS 50% AdjustmentR420 - PGI S.A.R422 - Platinum Guild International K.K.R423 - Platinum Guild International Hong Kong LimitedR425 - Platinum Guild International (U.S.A.) Jewelry, Inc.R426 - Platinum Guild India Private LimitedR427 - Platinum Guild International (Shangahai) Co., LtdR502 - Lexshell 49 General Trading Pty LtdR600 - The Platinum Producers' Environmental TrustR603 - RPM ESOP TrustR604 - Unki ESOP TrustR700 - Platmed (Pty) LtdR705 - Platmed Properties (Pty) Ltd</value>
      <webElementGuid>ae1e3774-8432-4c12-8225-728937163bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedCompanyCodesID1&quot;)</value>
      <webElementGuid>074277a0-add8-40a5-b6f5-a92e690073fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SelectedCompanyCodesID1']</value>
      <webElementGuid>652d8dd9-31aa-4691-95ae-40fb16b77df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detailsForm']/div[2]/div/select</value>
      <webElementGuid>a3103928-23a9-4e53-aedc-7dc51b646ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Codes'])[2]/following::select[1]</value>
      <webElementGuid>c2e1e8a0-74c0-4b74-ae7d-ade917c0270b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[2]/following::select[2]</value>
      <webElementGuid>6884257b-2ce3-488d-9107-0cedbd71bfc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance plant'])[3]/preceding::select[1]</value>
      <webElementGuid>a5ae0de7-98b6-40f8-a5d7-540e228c4446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/preceding::select[2]</value>
      <webElementGuid>11cd159d-0ed1-4ef1-825a-8fc4bfe74ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>f516e245-626f-46dc-80e2-e12756c7f1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SelectedCompanyCodesID1' and @name = 'SelectedCompanyCodesID1' and (text() = concat(&quot;Any Company CodeR000 - Rustenburg Platinum Mines LimtedR102 - Modikwa Platinum MineR149 - Modikwa JV EntriesR150 - Kroondal &amp; Marikana PSAR151 - The Work Expert Pty LtdR202 - Anglo Platinum Marketing Limited - UKR203 - APML - Adjustment EntityR204 - Anglo Platinum Marketing Limited - SGPR323 - Modikwa Platinum Mine PTYR324 - Modikwa Mining Personnel Services Pty LtdR325 - Matthey Rustenburg Refiners Pty LtdR332 - Unki Mines Private LimitedR333 - Amzim Holdings LimitedR334 - Erabas B.VR345 - Southridge LimitedR355 - Atomatic Trading (Pty) LtdR399 - MMPS 50% AdjustmentR420 - PGI S.A.R422 - Platinum Guild International K.K.R423 - Platinum Guild International Hong Kong LimitedR425 - Platinum Guild International (U.S.A.) Jewelry, Inc.R426 - Platinum Guild India Private LimitedR427 - Platinum Guild International (Shangahai) Co., LtdR502 - Lexshell 49 General Trading Pty LtdR600 - The Platinum Producers&quot; , &quot;'&quot; , &quot; Environmental TrustR603 - RPM ESOP TrustR604 - Unki ESOP TrustR700 - Platmed (Pty) LtdR705 - Platmed Properties (Pty) Ltd&quot;) or . = concat(&quot;Any Company CodeR000 - Rustenburg Platinum Mines LimtedR102 - Modikwa Platinum MineR149 - Modikwa JV EntriesR150 - Kroondal &amp; Marikana PSAR151 - The Work Expert Pty LtdR202 - Anglo Platinum Marketing Limited - UKR203 - APML - Adjustment EntityR204 - Anglo Platinum Marketing Limited - SGPR323 - Modikwa Platinum Mine PTYR324 - Modikwa Mining Personnel Services Pty LtdR325 - Matthey Rustenburg Refiners Pty LtdR332 - Unki Mines Private LimitedR333 - Amzim Holdings LimitedR334 - Erabas B.VR345 - Southridge LimitedR355 - Atomatic Trading (Pty) LtdR399 - MMPS 50% AdjustmentR420 - PGI S.A.R422 - Platinum Guild International K.K.R423 - Platinum Guild International Hong Kong LimitedR425 - Platinum Guild International (U.S.A.) Jewelry, Inc.R426 - Platinum Guild India Private LimitedR427 - Platinum Guild International (Shangahai) Co., LtdR502 - Lexshell 49 General Trading Pty LtdR600 - The Platinum Producers&quot; , &quot;'&quot; , &quot; Environmental TrustR603 - RPM ESOP TrustR604 - Unki ESOP TrustR700 - Platmed (Pty) LtdR705 - Platmed Properties (Pty) Ltd&quot;))]</value>
      <webElementGuid>02320cf7-2160-4c64-a294-eb7b2e88ba1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
