<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_This value is required</name>
   <tag></tag>
   <elementGuidId>0f8ff1ea-4046-471f-921a-4a38120c26f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.parsley-required</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='parsley-id-7']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a8ddbfe0-2e35-42a7-909b-2992faf6bd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>parsley-required</value>
      <webElementGuid>9107fe6b-ac50-4253-9015-b2d33bf96cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This value is required.</value>
      <webElementGuid>7abed53d-b788-432b-b5ca-4c39013ac86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parsley-id-7&quot;)/li[@class=&quot;parsley-required&quot;]</value>
      <webElementGuid>4bb8545a-91bf-45f5-9319-db2962d50808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='parsley-id-7']/li</value>
      <webElementGuid>a5e93c8f-36fe-4110-b5ff-23823012f3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Execution Platform'])[1]/following::li[1]</value>
      <webElementGuid>ff040311-3a0e-435b-9b16-3fceb997fe89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Anglo American &amp; De Beers Enterprise Applications. Please sign in to continue.'])[1]/following::li[1]</value>
      <webElementGuid>48c9463a-348c-48e7-955c-3a443a7920e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::li[1]</value>
      <webElementGuid>e6aaae2a-9e47-4e08-8c4f-f310429d6dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::li[1]</value>
      <webElementGuid>a74e1c43-9a39-41fe-abe9-e46ffd745e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This value is required.']/parent::*</value>
      <webElementGuid>f953219d-87fe-474b-b173-98c5bfa799ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>217928a3-a26c-4d53-a3d2-1621438c478d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'This value is required.' or . = 'This value is required.')]</value>
      <webElementGuid>fefd2570-2530-4eda-95ba-64bd5b125ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
