<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Email Templates_nav-icon icon-layers aa-primary</name>
   <tag></tag>
   <elementGuidId>f341a46a-b776-4972-a225-eae9ff55aad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='sidebar-nav-id']/ul/li[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.nav-icon.icon-layers.aa-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7c8e7e8d-a065-4a7c-9511-18807368b249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-icon icon-layers aa-primary</value>
      <webElementGuid>52c1d342-80ef-4dab-b6b4-72eeb916a243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav-id&quot;)/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item nav-dropdown&quot;]/a[@class=&quot;nav-link nav-dropdown-toggle hide-before w-100 aa-primary&quot;]/i[@class=&quot;nav-icon icon-layers aa-primary&quot;]</value>
      <webElementGuid>0e61ae8e-648c-4068-adce-9880653d7443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='sidebar-nav-id']/ul/li[3]/a/i</value>
      <webElementGuid>5921e7c8-2a3c-4fb6-b7fd-75823e482d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/i</value>
      <webElementGuid>d6b39b34-9177-478e-9c88-950c3fda6e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
