<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work End Time_form-control background-calendar-icon</name>
   <tag></tag>
   <elementGuidId>50a2f7ea-2ced-40cb-b09a-a9d7a12e5b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.align-items-start.pl-0 > div.pr-1.align-items-start.input-group > input.form-control.background-calendar-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f277da0-1014-496e-9778-01bc4aa8188c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48ba7f02-b7a1-45eb-bfb1-d306319e81d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control background-calendar-icon</value>
      <webElementGuid>5be999b8-35d0-4bca-9c09-7d3a7dd1e3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v-pills-tabContent&quot;)/div[@class=&quot;overflow-auto form-container whiteBg anglo-scrollbar&quot;]/div[@class=&quot;px-3 whiteBg&quot;]/div[@class=&quot;p-2 actual-work-background-group&quot;]/div[@class=&quot;d-flex align-items-start pl-0&quot;]/div[@class=&quot;pr-1 align-items-start  input-group&quot;]/input[@class=&quot;form-control background-calendar-icon&quot;]</value>
      <webElementGuid>c2ee0b2f-6738-4fb4-b5e8-b9806f804f84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>882e5a6b-1515-4e4d-bce9-0223446e8e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v-pills-tabContent']/div/div[2]/div[5]/div[4]/div/input</value>
      <webElementGuid>86d7b0af-990b-4877-ba6a-051fc9ea4020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>4f16c969-c5e1-4889-9b45-676ba0710954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>58ba4f33-d1f8-4499-aeeb-c38db88c7b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
