<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maintenance Request_followOnWorkRequestID</name>
   <tag></tag>
   <elementGuidId>e6c41574-18c1-4121-8941-964ecddaaa9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='followOnWorkRequestID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#followOnWorkRequestID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1876c6a9-1527-46e8-ad46-9b47f88eea89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5cd0fa3-b80e-4de6-91a9-f6fcb75d84e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>followOnWorkRequestID</value>
      <webElementGuid>877750f0-5295-41f7-8006-4e967e157ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>followOnWorkRequestID</value>
      <webElementGuid>676665a9-51d7-4db6-ae89-91c502e97dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-input cursorPointer</value>
      <webElementGuid>b3ba9912-99ab-4dd8-9350-b53f2dee3d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;followOnWorkRequestID&quot;)</value>
      <webElementGuid>56d8c1ff-43a8-4ccc-8150-b7f40d866fcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='followOnWorkRequestID']</value>
      <webElementGuid>df0bd13b-ccff-4ca1-b4f2-571f934b6b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>34c0b109-44e6-4c51-baea-32f0085580dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e46d392b-a0f7-49e5-ac13-c509c825797e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'followOnWorkRequestID']</value>
      <webElementGuid>c3599fce-9dad-41ea-b7cc-154548ef260e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
