<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bulkAPPROVE</name>
   <tag></tag>
   <elementGuidId>9cb76761-3464-4012-a0fc-04462d7bfc7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnApprove']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnApprove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd30ddfd-3932-491c-bed6-eb645d7b30a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9a74964-cc29-4ed1-aa23-5a3ae955e063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnApprove</value>
      <webElementGuid>6da63f74-f977-43e6-aa96-cd531e654a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnApprove</value>
      <webElementGuid>7f03a03a-3e98-4361-aac3-1fbb8d91e4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary custom-height px-5 font-weight-bold</value>
      <webElementGuid>b4e7d84c-4d56-4aac-b751-9632eddd7cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPROVE</value>
      <webElementGuid>7e95f923-f790-4a24-8e7c-3a95ed8c5c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn pb-3&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-lg-12 px-lg-1&quot;]/div[@class=&quot;card h-100 mb-0 rounded-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-horizontal ays-ignore w-100&quot;]/div[@class=&quot;d-none d-sm-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 pb-3 d-flex align-items-end justify-content-end&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;d-flex&quot;]/button[@id=&quot;btnApprove&quot;]</value>
      <webElementGuid>888d4495-8985-45af-8501-16df50c07081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnApprove']</value>
      <webElementGuid>9849f7bd-c2bc-4ad3-90d5-3b4bf7cf9dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div[2]/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>07384a1b-ef5c-4aee-aa9d-f5c9a70d06e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/following::button[1]</value>
      <webElementGuid>702aab3e-8677-42a6-9b71-fba1d84c3850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/following::button[1]</value>
      <webElementGuid>7106488c-e7df-48d8-a7a4-38c3159397eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REJECT'])[1]/preceding::button[1]</value>
      <webElementGuid>a357d4ca-717a-4935-9610-51d1f3c80c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Centre'])[2]/preceding::button[2]</value>
      <webElementGuid>22f2de41-9135-45eb-a58d-853cbf1db2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPROVE']/parent::*</value>
      <webElementGuid>2a8f10f4-cb2a-4cae-8a1e-1d5031903cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/button</value>
      <webElementGuid>df688abc-085f-4e14-9eb5-a9568837f199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnApprove' and @name = 'btnApprove' and (text() = 'APPROVE' or . = 'APPROVE')]</value>
      <webElementGuid>7b49989f-c040-49e0-b6e1-95fb7bc9d663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
