<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW_ALL</name>
   <tag></tag>
   <elementGuidId>80dc7fb4-1487-4d12-8ad0-fea8c4f851ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.aa-prrimary.mr-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-view']/div/div[2]/div/div/div[3]/div[4]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b36f9dd5-e404-4fb4-981d-7de5857456e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/WorkRequest/WorkRequestSapList</value>
      <webElementGuid>38dd1fd1-9b26-4c3e-a139-0d2bd058a9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aa-prrimary mr-2</value>
      <webElementGuid>34614ef9-4519-46c3-8406-750892898eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW_ALL</value>
      <webElementGuid>fc983290-0c9e-4ab7-9599-a752c54d11d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn px-0 py-4&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-md-6 pl-3 mb-3&quot;]/div[@class=&quot;panel h-100 d-flex flex-column px-2 bg-white position-relative&quot;]/div[@class=&quot;d-flex flex-column fixed-panel-no-overflow&quot;]/div[@class=&quot;d-flex justify-content-between align-items-end mt-2 mb-2&quot;]/a[@class=&quot;aa-prrimary mr-2&quot;]</value>
      <webElementGuid>e47483bc-45d5-4ef9-85ab-afc19886c9d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div[2]/div/div/div[3]/div[4]/a[2]</value>
      <webElementGuid>32edc4d8-e2f2-4b8a-aec2-92a9eebc75ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VIEW_ALL')]</value>
      <webElementGuid>0bfcb272-2a80-4e96-92da-a1a7963d31b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH ERP'])[1]/following::a[1]</value>
      <webElementGuid>0a6a5bbe-c4cb-48cc-9a47-2c0134b78485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[10]/following::a[2]</value>
      <webElementGuid>d2571d2c-e824-40e4-9611-f1607c0d308d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORK REQUESTS'])[2]/preceding::a[1]</value>
      <webElementGuid>fc54841f-9098-4da8-8656-f46efa47897f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Approval'])[1]/preceding::a[1]</value>
      <webElementGuid>7cdc34de-69fd-4c25-b946-4f5f28aa9192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIEW_ALL']/parent::*</value>
      <webElementGuid>da7d806b-8269-42ce-b529-c7a7ef7187a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/WorkRequest/WorkRequestSapList')])[2]</value>
      <webElementGuid>e33d2d57-2c76-4b10-993b-a8eba0e9bbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[2]</value>
      <webElementGuid>1dabcc8f-25f8-4755-bc5d-bc2dc61c4041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/WorkRequest/WorkRequestSapList' and (text() = 'VIEW_ALL' or . = 'VIEW_ALL')]</value>
      <webElementGuid>45f716e5-2bfc-4250-91e5-8fa242b6d53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[12]/following::a[2]</value>
      <webElementGuid>e59ad4b1-534d-4f9a-92cc-ce728775224c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
