<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_w-100 form-control round _01bf87</name>
   <tag></tag>
   <elementGuidId>8488bf35-4dfb-4749-88a7-e730db413e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.w-100.form-control.round.form-control-sm.mb-0.left-modal-text.inpusize.rounded-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdd200ff-8640-4f04-abb2-4b38ffb38faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c07343d1-5e2f-4d2f-9985-b2fd565c9796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c269ef17-7e02-40f6-9c8f-f6eaab55e87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 form-control round form-control-sm mb-0 left-modal-text inpusize rounded-0</value>
      <webElementGuid>34e4cf84-779a-4895-bf82-0c5974fedf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;info&quot;)/div[@class=&quot;overflow-auto form-container px-3&quot;]/div[@class=&quot;row align-items-start py-1 pl-3&quot;]/div[@class=&quot;col-8&quot;]/input[@class=&quot;w-100 form-control round form-control-sm mb-0 left-modal-text inpusize rounded-0&quot;]</value>
      <webElementGuid>96228c53-d50c-4ed0-be4d-740311c0ddf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>b5a1e201-f0cf-4729-8920-166265df0454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info']/div/div[6]/div[2]/input</value>
      <webElementGuid>ae7a5ca1-4bf0-4908-b357-8222912953e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7b3aed29-5011-4474-94c0-d876f7278b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>dc5a4d5e-2e7e-4ec8-ac3a-8953138cf7e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
