<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>workRequestObject</name>
   <tag></tag>
   <elementGuidId>76796004-1f1b-467e-9f03-a13c0c3e4719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;requestid1&quot;)/b[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='requestid1']/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#requestid1 > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>934b1945-2a09-454e-bff3-eb24c799d86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14453502</value>
      <webElementGuid>09ae246a-2184-4b53-b6ea-f1bbb1aa33bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requestid1&quot;)/b[1]</value>
      <webElementGuid>c682a69e-e17f-4edd-a9fa-b7c2d870b28e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='requestid1']/b</value>
      <webElementGuid>43675d38-55b7-4f00-bde5-cbfbef78a5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding'])[1]/following::b[1]</value>
      <webElementGuid>5840a73e-60a4-4ff8-9017-5f6d273a30c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The item was saved successfully'])[1]/preceding::b[1]</value>
      <webElementGuid>4d7c41d9-9394-44f4-bed7-6c3be7e72011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT'])[1]/preceding::b[1]</value>
      <webElementGuid>1ee6038a-a38b-47a7-9e25-908a9485e03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/b</value>
      <webElementGuid>d1b0c9b4-5a88-4676-9d71-78720a4ffece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '14453502' or . = '14453502')]</value>
      <webElementGuid>032a348e-06b7-46db-87e7-0b91f63b3661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
