<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xBTN</name>
   <tag></tag>
   <elementGuidId>c710562e-f607-4ece-aae8-637c254dfeda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='singleApprovalModal']/div/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-header.bg-white.d-flex.py-2.justify-content-between > button.close.aa-primary > img[alt=&quot;Close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32f68ae3-adc0-428d-a0c9-9ad6ca143fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/close.svg</value>
      <webElementGuid>573912a3-2b79-4a02-8751-989d08a43c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>1faca7e3-f3d3-4c99-a079-25fa8e87d913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>b3d9bda1-317a-4e03-80e0-131a5274dd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>dc14611b-43b7-4ebc-8869-77c02d293729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;singleApprovalModal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content rounded-0&quot;]/div[@class=&quot;modal-header bg-white d-flex py-2 justify-content-between&quot;]/button[@class=&quot;close aa-primary&quot;]/img[1]</value>
      <webElementGuid>3efdaf4c-267b-466f-9465-d27b4176ff1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singleApprovalModal']/div/div/div/button/img</value>
      <webElementGuid>36197390-55b7-4a36-85d0-49c2cd38f6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Close'])[2]</value>
      <webElementGuid>2f40358a-e3d6-4d86-bea8-970c65ee9c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button/img</value>
      <webElementGuid>f872f725-e8a6-448b-ac68-5b87e98cc787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/close.svg' and @alt = 'Close']</value>
      <webElementGuid>07048bb6-e5fe-4c1b-832b-f180c9504e6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
