<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sidebar-minimizerbtn</name>
   <tag></tag>
   <elementGuidId>8017cf66-2d86-4252-82ef-c424ef579237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sidebar-minimizer.brand-minimizer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b292fd9-5036-4d39-a962-879fccf5d936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-minimizer brand-minimizer</value>
      <webElementGuid>84331d5b-ed97-446d-82e3-912b4d95909b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SetSessionValue()</value>
      <webElementGuid>350009f8-48be-4c54-9391-e53e9314e2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf6cabf5-91f0-4510-a899-0bc526a22ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show brand-minimized sidebar-minimized     pace-done pace-done&quot;]/div[@class=&quot;app-body anglo-scrollbar&quot;]/div[@class=&quot;sidebar&quot;]/div[@class=&quot;sidebar-bottom-wrapper&quot;]/button[@class=&quot;sidebar-minimizer brand-minimizer&quot;]</value>
      <webElementGuid>fe524906-42bd-4ff7-910e-069418bb53dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>59d6a2e0-dc05-4960-88cb-39e021fc8f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>7df307f9-6644-4fd5-8eb3-f4b4d761438b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>8e99359e-5e79-4736-8a5e-7df1df720fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
