<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Business Units</name>
   <tag></tag>
   <elementGuidId>072267a1-d165-440c-a905-87eab742e256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-sub-bu']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-sub-bu > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9fa899f1-0b7d-4d67-829f-6ef5a9691736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/MasterData/BusinessUnitList</value>
      <webElementGuid>fab08b6e-2240-4bca-a8ef-fc68d27a8768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business Units </value>
      <webElementGuid>14437d52-9434-4a73-87ff-a90e19715820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-sub-bu&quot;)/a[1]</value>
      <webElementGuid>86dd7e0b-7a87-4be9-a885-f0403f492fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-sub-bu']/a</value>
      <webElementGuid>b4ba3c72-5075-427e-866d-8c089e184243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Business Units')]</value>
      <webElementGuid>d005d0eb-75cf-4f96-b0e4-d117631e9c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User MD Hash'])[1]/following::a[1]</value>
      <webElementGuid>b2ea5028-6d41-4248-967d-d000bf9191f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::a[2]</value>
      <webElementGuid>e27be2dc-0f96-44eb-9d81-a66bce959c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Units sites'])[1]/preceding::a[1]</value>
      <webElementGuid>13ac251c-cd15-4035-98c0-fdcbd9be702d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Units site areas'])[1]/preceding::a[2]</value>
      <webElementGuid>617fd4ed-aa30-4766-8dc6-0cbb55faf793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Business Units']/parent::*</value>
      <webElementGuid>726fe865-29bf-4a62-9900-833197185792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/MasterData/BusinessUnitList')]</value>
      <webElementGuid>ed0fcef4-51b3-4397-8b75-eed6a201f4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>80c07c3c-f9db-44eb-a011-fb4f327fc5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/MasterData/BusinessUnitList' and (text() = 'Business Units ' or . = 'Business Units ')]</value>
      <webElementGuid>74fe1730-a266-41dc-8ede-2a95fce693bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
