<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shift Types</name>
   <tag></tag>
   <elementGuidId>986f71df-77f7-4665-8c4e-7b3aae3acbff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-sub-st']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-sub-st > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7b761f0-a104-4158-a677-356bf3ec01c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/MasterData/ShiftTypeList</value>
      <webElementGuid>3c1fefec-b39b-4448-993f-729fc910fa3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shift Types</value>
      <webElementGuid>7c65796a-68f7-4384-95e2-d61e76c8d914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-sub-st&quot;)/a[1]</value>
      <webElementGuid>b055e8be-a7e4-4689-a2f1-76ac7f62e0c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-sub-st']/a</value>
      <webElementGuid>9238d47f-adb4-4fe0-a5d5-b14252b71a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shift Types')]</value>
      <webElementGuid>38d37843-b8dd-40eb-a80e-f2c382e9d53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Periods'])[3]/following::a[1]</value>
      <webElementGuid>47b9e570-e758-44dd-b926-4986b6919719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Areas'])[1]/following::a[2]</value>
      <webElementGuid>abebb131-ced0-408a-8c4d-042c5f1e7107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[1]/preceding::a[1]</value>
      <webElementGuid>6da76405-a61a-4a07-993d-4ef8afc5a05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment Types'])[1]/preceding::a[2]</value>
      <webElementGuid>787fe29b-5cdb-4cf8-a73c-8a24c9447068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shift Types']/parent::*</value>
      <webElementGuid>93189ce3-fe3a-47c2-84d9-4092c4052e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/MasterData/ShiftTypeList')]</value>
      <webElementGuid>a33c16a7-b7e8-4b6f-bd3e-ef3a17f793a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[7]/a</value>
      <webElementGuid>23b12ec7-45c0-4a31-8e73-34358c29a2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/MasterData/ShiftTypeList' and (text() = 'Shift Types' or . = 'Shift Types')]</value>
      <webElementGuid>b24c3ee6-b60a-4ae1-9c19-6da3ffc8a452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
