<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_AddSite</name>
   <tag></tag>
   <elementGuidId>8d2505c9-a816-4c1b-bff4-a963a17b935f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div/form/div/div[4]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pli-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9dfaf803-9c8a-4ce5-96f4-3b0522ac1e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pli-plus</value>
      <webElementGuid>5cdb4dde-8ffc-41d0-800f-b309cff72824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;panel&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[1]/div[@class=&quot;col-md-1 text-right&quot;]/a[@class=&quot;btn btn-primary btn-icon btn-circle&quot;]/i[@class=&quot;pli-plus&quot;]</value>
      <webElementGuid>284cdb3f-a787-4a8c-a7f9-74ff474b86ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/form/div/div[4]/a/i</value>
      <webElementGuid>ea4e9aba-d7c1-490c-8725-fa83077e0f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/i</value>
      <webElementGuid>b79a7eb6-afc2-4a8a-9440-8e675ec2f6e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
