<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Active_btn btn-danger btn-icon btn-sm btnRemove</name>
   <tag></tag>
   <elementGuidId>6289bec9-9ece-4f3f-8f00-4720b0986085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dt-table']/tbody/tr/td/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.btn-icon.btn-sm.btnRemove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>568020de-9d15-44d7-8269-a06eeeca2765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-icon btn-sm btnRemove</value>
      <webElementGuid>f67053ff-1dfa-48a0-8386-db5db8d5794c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>93186253-3a19-48cc-9a4e-96724d6c08c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>57dece84-b993-4575-991b-d87d6e5e4638</value>
      <webElementGuid>f07c94c8-bfe3-4810-a82e-fe7aa7100d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Automation IM 3</value>
      <webElementGuid>0eb9b540-7283-489a-8e2a-e7b637a44b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dt-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]/button[@class=&quot;btn btn-danger btn-icon btn-sm btnRemove&quot;]</value>
      <webElementGuid>8dbd54a2-1a07-42bf-81df-8e4506bcd7ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dt-table']/tbody/tr/td/button</value>
      <webElementGuid>64b68b37-8a05-4aa5-9334-c814fa1be94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::button[1]</value>
      <webElementGuid>54f54623-e573-40af-bd1c-e86e3354625a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::button[1]</value>
      <webElementGuid>6e304545-32ee-4677-a6fc-672e912f50d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation IM 3'])[1]/preceding::button[1]</value>
      <webElementGuid>7420e8c2-5454-4b19-a5d7-53a1222c336d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AIM 3'])[1]/preceding::button[1]</value>
      <webElementGuid>7f36ee5d-b832-44ad-8821-3e6ccb81b0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>5a40f67c-5af6-40ed-9f17-5c0d272052d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@alt = 'Remove']</value>
      <webElementGuid>4c22b18a-30ae-4205-b713-744156fd8ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
