<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add_Search_pli-plus</name>
   <tag></tag>
   <elementGuidId>6b2c38c5-0352-4024-bc0d-968a8411feab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div/form/div/div[5]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pli-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>624d4ef2-a4aa-4c3a-b915-db5ca7acbad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pli-plus</value>
      <webElementGuid>46968877-dea5-424e-8a12-ce94103c8e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;panel&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[1]/div[@class=&quot;col-md-1 text-right&quot;]/a[@class=&quot;btn btn-primary btn-icon btn-circle&quot;]/i[@class=&quot;pli-plus&quot;]</value>
      <webElementGuid>1be4e739-959e-4118-84cb-9a7db70d3977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/form/div/div[5]/a/i</value>
      <webElementGuid>629715bb-5476-4a86-9b3a-42225698f39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/i</value>
      <webElementGuid>c77b8e80-8d71-4405-a0d5-832815c7d30a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
