<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_BtnAdd_SiteArea</name>
   <tag></tag>
   <elementGuidId>8fac1010-0b63-4db9-8159-57807d76ed8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.pli-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div/form/div/div[5]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9db0e255-632a-47ee-87ab-c204cbf087ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pli-plus</value>
      <webElementGuid>3bef2634-bb35-4070-bff9-468860a44e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;panel&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[1]/div[@class=&quot;col-md-1 text-right&quot;]/a[@class=&quot;btn btn-primary btn-icon btn-circle&quot;]/i[@class=&quot;pli-plus&quot;]</value>
      <webElementGuid>b0627297-2f8a-4bad-86e3-3706c6fc532d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/form/div/div[5]/a/i</value>
      <webElementGuid>614451d2-aa5a-44e7-be55-cedb5096beaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/i</value>
      <webElementGuid>3dba877b-bf52-4fe4-8ed6-c40723c0f1f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
