<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search_pli-plus</name>
   <tag></tag>
   <elementGuidId>7e8cb839-b029-4c69-879c-ffd8fd963abd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-master-data']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-master-data > a > i.arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>365ed3b7-fce8-48f7-9e56-e95f5bea083a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>cc0bcdd3-a926-4171-96b7-ecfb567dbd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-master-data&quot;)/a[1]/i[@class=&quot;arrow&quot;]</value>
      <webElementGuid>d0bb28f0-3ee9-409e-beda-bd22283e932a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-master-data']/a/i</value>
      <webElementGuid>ec844c8b-4463-4249-a5c5-c68cd2a2abce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/i</value>
      <webElementGuid>60abc91e-4d0b-431b-a0b0-57ce88a75cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/form/div/div[5]/a/i</value>
      <webElementGuid>36a21a58-ea1b-4a8b-aad5-6cdfc5262bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/i</value>
      <webElementGuid>a098aab4-a259-4df0-8d76-edb8a239f4b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
