<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work Orders Menu Item</name>
   <tag></tag>
   <elementGuidId>f1f53d79-ab95-4d1a-b6ed-e50cb1389659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.nav-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='nav-item nav-dropdown'][3]/a[@class='nav-link aa-primary nav-dropdown-toggle hide-before w-100 cursorPointer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>596bbe8f-f4e3-4ab0-a077-85f4919cc7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-icon</value>
      <webElementGuid>55129048-7149-47d0-b5ce-cde2173b98c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/icon-work-orders-blue.svg</value>
      <webElementGuid>eec4b0f7-8892-48d7-ad91-70491225e0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>4d4c057a-6320-441f-b66b-56ade38f8849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c81f5968-1f58-4b3a-b770-eecd9bb05f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav-id&quot;)/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item nav-dropdown&quot;]/a[@class=&quot;nav-link aa-primary nav-dropdown-toggle hide-before w-100 cursorPointer&quot;]/img[@class=&quot;nav-icon&quot;]</value>
      <webElementGuid>aee91232-ad5a-4669-9222-f4dfcd504237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='sidebar-nav-id']/ul/li[3]/a/img</value>
      <webElementGuid>44a5efe6-42c1-462a-b108-aef3f5ab138c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>8997e42b-f4c6-47d1-a2c0-55b0085a2e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/icon-work-orders-blue.svg']</value>
      <webElementGuid>ac6cdfe1-2db9-4a75-b63a-8b76672feae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
