<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Work Requests</name>
   <tag></tag>
   <elementGuidId>2c032f72-86fb-4d80-a7b9-33da0fd2f908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-item.mr-2 > a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/nav/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c3f8f6d-6b8b-44a3-8d8f-b1125cc6fe7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/workrequest/WorkRequestSapList</value>
      <webElementGuid>fd42c650-2aca-4d67-8374-784d19a41dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>4b99170a-0c23-4b2e-a5d0-e875fa6f4996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Work Requests</value>
      <webElementGuid>f322dcbd-8179-40dd-ae94-90876288fddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/nav[@class=&quot;navbar navbar-expand-lg navbar-light mb-0  pb-0 align-items-end&quot;]/ul[@class=&quot;navbar-nav mr-auto&quot;]/li[@class=&quot;nav-item  mr-2&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>d0e02799-3ee2-4689-b7fe-8a30b347482b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/nav/ul/li/a</value>
      <webElementGuid>2e665e6d-e0e8-46f4-990d-13919a87bc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'My Work Requests')])[2]</value>
      <webElementGuid>faf2396d-ef98-4c19-81a3-66945793832a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Requests'])[2]/following::a[1]</value>
      <webElementGuid>3776b593-ca3c-49a5-b6a1-360af52ae8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>85559a30-df02-4ff7-a68d-cb8d3e406b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending approval'])[2]/preceding::a[2]</value>
      <webElementGuid>1a19f14f-253b-4723-8349-84bcb0035f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search ERP by'])[1]/preceding::a[3]</value>
      <webElementGuid>8c1af476-38a2-4ab3-8a62-fe819acf709c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/workrequest/WorkRequestSapList')]</value>
      <webElementGuid>14e148d9-3ae7-448a-8996-780caec1ac10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/nav/ul/li/a</value>
      <webElementGuid>35f7f669-5510-4561-8113-4c96d252422a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/workrequest/WorkRequestSapList' and (text() = 'My Work Requests' or . = 'My Work Requests')]</value>
      <webElementGuid>01e5cac7-694c-4ba9-9f9c-377b33d9840a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
