<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FunctionalLocationRadio</name>
   <tag></tag>
   <elementGuidId>42fbb12a-649b-4858-8551-d6d1bdbdca84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='functionalLocationRadio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#functionalLocationRadio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f67bc62-7da0-4f42-b11f-d8dfe636aee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4efa97eb-c7ce-4a8c-b4db-de3404c2fd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Option</value>
      <webElementGuid>ce91fede-4df6-4d4f-911c-bb3f64936ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a50961f2-62b1-47c5-a50f-973d91ad1294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>functionalLocationRadio</value>
      <webElementGuid>ff8f0415-db74-4e3d-8451-d0c0b5418d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mt-1</value>
      <webElementGuid>3035aaf5-1199-477e-9f3a-1d5d9c7b9069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn pb-3&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-lg-12 px-lg-1&quot;]/div[@class=&quot;card h-100 mb-0 rounded-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-sm-block d-none&quot;]/div[@class=&quot;pr-3 pl-3 pb-1 d-flex&quot;]/div[@class=&quot;col-12 col-md-3 flex-column align-items-start justify-content-start border-right border-bottom&quot;]/label[@class=&quot;label-custom-color d-flex&quot;]/input[@id=&quot;functionalLocationRadio&quot;]</value>
      <webElementGuid>6ae7c350-730a-4474-8e24-c1fd1b6c1751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='functionalLocationRadio']</value>
      <webElementGuid>4f255bef-e9bc-4f59-8e49-ce23691ace55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div/div/div[2]/div/label[3]/input</value>
      <webElementGuid>ef2ddef6-f066-4418-8f7d-84b62c737bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>4c01a59d-3bef-4208-b038-218107a99328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Option' and @id = 'functionalLocationRadio']</value>
      <webElementGuid>8c6b6001-dec5-4da9-8fde-e2ab7495a971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
