<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>getWRNumber</name>
   <tag></tag>
   <elementGuidId>17abf532-d92f-476c-aed9-fe3f67b343bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#requestid1 > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='requestid1']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>939188d2-a275-4ffa-89ad-79e220124b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15052947</value>
      <webElementGuid>7aa02bda-8452-4b20-9f50-830d5ec9dba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requestid1&quot;)/b[1]</value>
      <webElementGuid>0ebc86ae-6f55-4012-8597-7a2cc18c25b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='requestid1']/b</value>
      <webElementGuid>095e8359-2858-4abf-a545-a4b099e82d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::b[1]</value>
      <webElementGuid>f4ded028-b5a9-4f13-9683-a3055a9cf177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/preceding::b[1]</value>
      <webElementGuid>f0587e7d-7c38-4dfc-a231-e1ba30f70d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Status'])[1]/preceding::b[1]</value>
      <webElementGuid>120c655a-54b7-4bef-b0be-63052c2e70a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/b</value>
      <webElementGuid>189938a6-7438-49c7-b2ce-8cca9def5210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '15052947' or . = '15052947')]</value>
      <webElementGuid>33d95689-7088-400f-8910-af9676c45e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
