<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Work Request number_WorkReques_08e5c7</name>
   <tag></tag>
   <elementGuidId>eba41d1b-dfba-444e-b277-341d79ea5d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WorkRequestListLookup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WorkRequestListLookup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b3e8b55-4d5e-4a4a-b47c-8235b283521f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WorkRequestListLookup</value>
      <webElementGuid>444f7bcf-dae8-4ae4-93ee-7fc7e0e6754a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Work Request number</value>
      <webElementGuid>c0391cfe-3009-4380-a343-be6dab402bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>94630223-e155-410e-bcda-a03003f06b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search rounded-0 w-100</value>
      <webElementGuid>b5cbb93a-adc1-45d1-8c04-fa58896ec3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn pb-3&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-lg-12 px-lg-1&quot;]/div[@class=&quot;card h-100 mb-0 rounded-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-sm-block d-none&quot;]/div[@class=&quot;pr-3 pl-3 pb-1 d-flex&quot;]/div[@class=&quot;pb-3 col-md-9 col-12 d-flex border-bottom&quot;]/div[@class=&quot;col-md-9 col-12&quot;]/div[@class=&quot;row form-group d-flex align-items-end flex-wrap&quot;]/div[@class=&quot;col-md-6 col-12 px-0 mr-3&quot;]/input[@id=&quot;WorkRequestListLookup&quot;]</value>
      <webElementGuid>c793e610-2d58-492b-8c2a-45b98afca694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WorkRequestListLookup']</value>
      <webElementGuid>74788c0d-ea26-4fd7-9a82-86be77e8eebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div/div/div[2]/div[2]/div/div/div/input[2]</value>
      <webElementGuid>27c1e056-6122-4bf5-b128-dba4f8420dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>503c2b4d-4161-4c53-89e1-8e4236201b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'WorkRequestListLookup' and @placeholder = 'Work Request number' and @type = 'search']</value>
      <webElementGuid>1e32e781-ca58-4a70-b426-fdc348544653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
