<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mostRecentRadio</name>
   <tag></tag>
   <elementGuidId>5c917914-bf9c-4677-a8b4-ec3ba75d33d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mostRecent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mostRecent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5990e70-484d-47dd-8fc2-94f21cc91952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7dacc359-f246-4a5c-9292-66ad91db1fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Option2</value>
      <webElementGuid>992d0fe2-f82e-4621-8a03-57e85d69d87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>06a4bb53-4970-4271-a7b5-9ad0345f15c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mostRecent</value>
      <webElementGuid>85777e0b-1e04-4905-9d12-f005718fb125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>ec01bdfd-daaa-46c5-af11-db0e23319f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mt-1</value>
      <webElementGuid>bfc4fcde-45fd-436c-a53d-211c567cd9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn pb-3&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-lg-12 px-lg-1&quot;]/div[@class=&quot;card h-100 mb-0 rounded-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-sm-block d-none&quot;]/div[@class=&quot;pr-3 pl-3 pb-1 d-flex&quot;]/div[@class=&quot;pb-3 col-md-9 col-12 d-flex border-bottom&quot;]/div[@class=&quot;col-md-9 col-12&quot;]/div[@id=&quot;dateFromTo&quot;]/div[@class=&quot;col-12 flex-column&quot;]/div[@class=&quot;label-custom-color d-flex&quot;]/label[1]/input[@id=&quot;mostRecent&quot;]</value>
      <webElementGuid>7af49c9b-091f-4cca-8225-211a2523020d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mostRecent']</value>
      <webElementGuid>c77df030-6b4c-44d8-87bd-7a81508bed28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateFromTo']/div/div/label/input</value>
      <webElementGuid>cacc7dc3-a3ce-4c98-96ff-046f7499900c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/input</value>
      <webElementGuid>d5523662-9c9f-4ab0-a9c0-4066908fcb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Option2' and @id = 'mostRecent' and @checked = 'checked']</value>
      <webElementGuid>3e989a05-2a25-43c2-9c2c-3e487b4b97aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
