<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Button</name>
   <tag></tag>
   <elementGuidId>c497234a-ff62-494e-9f58-32e056741077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.mt-2.px-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68479507-3fd3-4f34-aaef-c321885a07c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfa4f845-78f0-44e4-93ec-b730ad2484b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mt-2 px-5</value>
      <webElementGuid>7dca66cd-74b6-4774-a919-db8831f7c9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            SEARCH
                                                        </value>
      <webElementGuid>821e8440-e298-445a-b342-85a02f43ec6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn pb-3&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-lg-12 px-lg-1&quot;]/div[@class=&quot;card h-100 mb-0 rounded-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-sm-block d-none&quot;]/div[@class=&quot;pr-3 pl-3 pb-1 d-flex&quot;]/div[@class=&quot;pb-3 col-md-9 col-12 d-flex border-bottom&quot;]/div[@class=&quot;col-md-9 col-12&quot;]/div[@class=&quot;row form-group d-flex&quot;]/div[@class=&quot;flex-grow-0 pb-2&quot;]/button[@class=&quot;btn btn-primary mt-2 px-5&quot;]</value>
      <webElementGuid>81adb097-e191-4d5e-9912-64d3f401f4c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>69d04192-872d-4e10-90b0-3eab31334af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div/div/div[2]/div[2]/div/div[3]/div/button</value>
      <webElementGuid>2e4b0699-950c-491e-92b6-b5b6a83efbd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For specific date range'])[1]/following::button[1]</value>
      <webElementGuid>56d7199a-8b40-4482-8468-30b2d5dfe0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Most recent'])[1]/following::button[1]</value>
      <webElementGuid>a3cfe7fa-c331-40dc-82a2-7256828282a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::button[1]</value>
      <webElementGuid>07c04c15-00b7-4fe4-9294-d4e1ef2f7dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding'])[1]/preceding::button[1]</value>
      <webElementGuid>aaf89eaa-bdaa-4f2a-9fc1-247bf22af670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>b63870a9-df25-4ca9-adb1-a43d70ecad2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>18806927-adab-4ae0-b515-85dfc47dc627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                                            SEARCH
                                                        ' or . = '
                                                            SEARCH
                                                        ')]</value>
      <webElementGuid>10176d8d-1f62-459c-9150-d67cae980341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
