<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work Request Number Option</name>
   <tag></tag>
   <elementGuidId>7f639d15-1543-44da-9100-93ad0a899e1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workRequestNumberRadio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workRequestNumberRadio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f017141d-7f49-4896-8729-8edd44088e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b0699edd-5b23-480c-b8c7-d2bca2faa74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Option</value>
      <webElementGuid>f017652c-ea63-4d7f-837e-dfbe9e7b0797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>83b0408f-eaeb-4c67-8bd3-89455d258c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workRequestNumberRadio</value>
      <webElementGuid>493041d0-b120-47cc-a4d0-4040c2e84901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mt-1</value>
      <webElementGuid>d3026af9-da56-42bc-a544-a1cc297d11cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn pb-3&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-lg-12 px-lg-1&quot;]/div[@class=&quot;card h-100 mb-0 rounded-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-sm-block d-none&quot;]/div[@class=&quot;pr-3 pl-3 pb-1 d-flex&quot;]/div[@class=&quot;col-12 col-md-3 flex-column align-items-start justify-content-start border-right border-bottom&quot;]/label[@class=&quot;label-custom-color d-flex&quot;]/input[@id=&quot;workRequestNumberRadio&quot;]</value>
      <webElementGuid>026504ba-9184-41e0-a1a3-411d8fbb0044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workRequestNumberRadio']</value>
      <webElementGuid>b323c5f5-fefc-4420-a21a-ff294b27a166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div/div/div[2]/div/label[5]/input</value>
      <webElementGuid>7ae0bd99-c21c-4e34-a725-c0cca6ca1f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[5]/input</value>
      <webElementGuid>4ac96f9d-2c36-46d1-ab85-fe733fd3668e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Option' and @id = 'workRequestNumberRadio']</value>
      <webElementGuid>426e7c74-3fda-42ad-843b-15f570a9c362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
