<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FL-ERPSelect</name>
   <tag></tag>
   <elementGuidId>98e75c91-0c57-494b-9026-e0a23aa0c39d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mr-2.border-left.pl-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vueAppFLHierarchy']/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ac0e77fc-684f-4cdd-ac6f-bba13ff53283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png</value>
      <webElementGuid>ccf5a9d9-ac81-4ee5-87bc-30d02efa38f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>dd1a67ed-70a0-4664-8df6-fb10e502d523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 border-left pl-2</value>
      <webElementGuid>d7083321-b28d-47f8-9a10-0f645c43da57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppFLHierarchy&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;overflow-auto ml-2 mr-2 anglo-scrollbar&quot;]/div[1]/div[@class=&quot;d-flex wiz-list-item c-pointer py-2 border-bottom&quot;]/div[@class=&quot;d-flex align-self-center w-50 justify-content-end&quot;]/img[@class=&quot;mr-2 border-left pl-2&quot;]</value>
      <webElementGuid>30084ef2-4b51-4898-b410-81539d38153b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppFLHierarchy']/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      <webElementGuid>08887139-daa8-497a-a1cd-e75e978aa068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png')]</value>
      <webElementGuid>1420f8ee-7650-4622-acc1-1dbb9a1f5a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>73b970bd-3e55-4f89-8b1d-91a255008882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://wep-preprod.ea.angloamerican.com/img/icon-compass-select@x2.png']</value>
      <webElementGuid>f1b82ad4-9c62-4109-bc3a-410b7cf7d784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
