<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SEARCH ERP (1)</name>
   <tag></tag>
   <elementGuidId>f685be6e-07d2-4f26-b001-6c105aae9556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-view']/div/div/div/div/div[3]/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.aa-primary.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0292dba0-bcf2-486c-b0ec-825e0c065b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/WorkRequest/WorkRequestSapSearchERPList</value>
      <webElementGuid>d8f5328c-ba8d-4fb8-9ffd-c92f8954c629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aa-primary mr-2</value>
      <webElementGuid>a08da525-5b86-4053-875e-e3d6aa5a6a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH ERP</value>
      <webElementGuid>6a08f897-b5a1-4573-93e4-3adb90ab3776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-view&quot;)/div[@class=&quot;animated fadeIn px-0 py-4&quot;]/div[@class=&quot;row mx-lg-n1&quot;]/div[@class=&quot;col-md-6 pl-3 mb-3&quot;]/div[@class=&quot;panel h-100 d-flex flex-column px-2 bg-white position-relative&quot;]/div[@class=&quot;d-flex flex-column fixed-panel-no-overflow&quot;]/div[@class=&quot;d-flex justify-content-between align-items-end mt-2 mb-2&quot;]/a[@class=&quot;aa-primary mr-2&quot;]</value>
      <webElementGuid>3c25f480-85ce-48e9-8f77-cfb97325bd71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-view']/div/div/div/div/div[3]/div[4]/a</value>
      <webElementGuid>c20dc08b-8f70-4385-85a4-a0196089b418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SEARCH ERP')]</value>
      <webElementGuid>b172cf23-6f86-44d0-95df-a57ee6083aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[8]/following::a[1]</value>
      <webElementGuid>5787b726-0ff9-4198-9b4b-c2000b53133f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Production Request'])[2]/following::a[1]</value>
      <webElementGuid>5de6ef74-ed7d-4787-9c52-dfaed07de20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW_ALL'])[1]/preceding::a[1]</value>
      <webElementGuid>7e8fbffc-210a-4505-bbd8-c13be13d53fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORK REQUESTS'])[2]/preceding::a[2]</value>
      <webElementGuid>94f58324-248c-49a0-bf50-f0294b1bce0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH ERP']/parent::*</value>
      <webElementGuid>717d7f87-1163-4f89-83b3-29d56bd2d2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/WorkRequest/WorkRequestSapSearchERPList')])[2]</value>
      <webElementGuid>055bcafa-7df3-4d7f-b980-2454c2692a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>080c43dc-7057-48cc-b886-4e0c3333590f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/WorkRequest/WorkRequestSapSearchERPList' and (text() = 'SEARCH ERP' or . = 'SEARCH ERP')]</value>
      <webElementGuid>a4609840-9a7b-4361-977b-c1147a323f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
