<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_High  High</name>
   <tag></tag>
   <elementGuidId>3698d756-7216-4275-a430-65d8ec134775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-8.col-md-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>268b01ee-2bde-4b4c-ad8d-1d2aaa083f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-8 col-md-10</value>
      <webElementGuid>b5a8d363-e05c-4a4d-836e-5024a4dfa8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>High  High</value>
      <webElementGuid>fba3b71e-d3bb-4749-be68-c3003652296e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vueAppContainer1&quot;)/div[@class=&quot;card h-100&quot;]/div[@class=&quot;form-horizontal mar-top flex-column d-flex h-100 justify-content-start&quot;]/div[@class=&quot;card-body h-100 d-flex flex-column pt-0 px-0&quot;]/div[@class=&quot;overflow-auto px-3&quot;]/div[@class=&quot;d-flex wiz-list-item c-pointer py-2 border-bottom&quot;]/div[@class=&quot;col-8 col-md-10&quot;]</value>
      <webElementGuid>e6183721-3f7c-40c3-9634-6eeaf22ed4be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vueAppContainer1']/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>b4f89b67-e487-4812-acf3-4ace48af2083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[9]/following::div[1]</value>
      <webElementGuid>9147b24d-1017-4bd2-95df-8e0fff89a38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impact'])[4]/following::div[9]</value>
      <webElementGuid>457fdc5d-26a4-4b72-bc85-e221a4f34eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>8e3ba665-97b0-4b50-a76b-aebfe6897748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'High  High' or . = 'High  High')]</value>
      <webElementGuid>bd70bb08-71be-48ef-8332-694b42175115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
