<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Active_psi-pen-5 icon-sm</name>
   <tag></tag>
   <elementGuidId>3e4639ee-aae2-4780-b723-fc5d2639ada2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.psi-pen-5.icon-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dt-table']/tbody/tr/td/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a26cf36f-b5cd-4eb9-9584-98f57ee1ba70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>psi-pen-5 icon-sm</value>
      <webElementGuid>29cf45c5-7223-4fde-a172-c82912c20588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dt-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]/a[@class=&quot;btn btn-mint btn-icon btn-sm&quot;]/i[@class=&quot;psi-pen-5 icon-sm&quot;]</value>
      <webElementGuid>769f38df-b083-411b-bfbb-3930b3541e70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dt-table']/tbody/tr/td/a/i</value>
      <webElementGuid>0abae339-8d9f-4989-a564-6a332e41a4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/i</value>
      <webElementGuid>e1fb6dcd-0021-4d3c-a276-932856451b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
