<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Equipment number_EquipmentNumber (2)</name>
   <tag></tag>
   <elementGuidId>416b1f9a-6db7-4812-bf6f-b0c555f501db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EquipmentNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EquipmentNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Equipment number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e3af013-fda5-427e-9ba1-d68be08c3f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2161fe83-dc9f-4930-87af-5463aeff1326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EquipmentNumber</value>
      <webElementGuid>9466136a-0778-4792-93e3-11a4174ea789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EquipmentNumber</value>
      <webElementGuid>9d63b8d2-b315-466c-bb7a-7fc188d8f716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>788131bc-d807-4363-ba0c-752ecf7e5ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>EquipmentNumber</value>
      <webElementGuid>eece6038-fccd-4398-a7ca-a6b70b03572b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EquipmentNumber&quot;)</value>
      <webElementGuid>0dfdb60d-2bef-4633-8b76-87e11d741381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EquipmentNumber']</value>
      <webElementGuid>960e9e9d-c11d-4fc6-a3ce-a27cd54b74f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detailsForm']/div/div/div/div/input</value>
      <webElementGuid>03590db8-2d77-4e7e-a68b-d0ecc7308a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b0574a84-cf3e-45ee-90ed-42fb6456e312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'EquipmentNumber' and @name = 'EquipmentNumber']</value>
      <webElementGuid>4ab06e39-d90a-4735-af4b-2c6404a8b95e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
